'use client'

import { useState, useEffect, useRef, useCallback } from 'react'
import { useRouter, useSearchParams } from 'next/navigation'
import dynamic from 'next/dynamic'
import toast from 'react-hot-toast'
import './editor.css'

const TiptapEditor = dynamic(() => import('@/components/editor/tiptap-editor'), {
  ssr: false,
  loading: () => <div className="te-loading" />,
})

const FeaturedImagePicker = dynamic(() => import('@/components/editor/featured-image-picker').then(m => ({ default: m.FeaturedImagePicker })), {
  ssr: false,
  loading: () => <div className="fi-placeholder" style={{ padding: 24, color: 'var(--g400)' }}>Loading...</div>,
})

const AISidebar = dynamic(() => import('@/components/editor/ai-sidebar').then(m => ({ default: m.AISidebar })), {
  ssr: false,
  loading: () => null,
})

const EVENT_TO_CATEGORY: Record<string, string> = {
  'TRANSFER': 'transfers', 'CONTRACT': 'transfers', 'INJURY': 'injuries',
  'MATCH_PREVIEW': 'matches', 'MATCH_RESULT': 'matches', 'POST_MATCH_REACTION': 'matches',
  'BREAKING': 'news', 'SCANDAL': 'news', 'DISCIPLINE': 'news', 'RECORD': 'news',
  'MANAGERIAL': 'news', 'TACTICAL': 'news',
}

export default function EditorPageInner() {
  const router = useRouter()
  const searchParams = useSearchParams()
  const [title, setTitle] = useState('')
  const [subtitle, setSubtitle] = useState('')
  const [content, setContent] = useState<Record<string, unknown>>({})
  const [initialContent, setInitialContent] = useState<Record<string, unknown> | undefined>(undefined)
  const [saving, setSaving] = useState(false)
  const [publishedStatus, setPublishedStatus] = useState<'DRAFT' | 'PUBLISHED' | 'SCHEDULED'>('DRAFT')
  const [siteId, setSiteId] = useState<string | null>(null)
  const [categories, setCategories] = useState<Array<{ id: string; name: string; slug?: string; icon?: string }>>([])
  const [categoryId, setCategoryId] = useState('')
  const [showAI, setShowAI] = useState(false)
  const [aiResult, setAiResult] = useState<{ model?: string; tokensIn?: number; tokensOut?: number } | null>(null)
  const [sendNewsletter, setSendNewsletter] = useState(false)
  const [showSEO, setShowSEO] = useState(false)
  const [metaTitle, setMetaTitle] = useState('')
  const [metaDesc, setMetaDesc] = useState('')
  const [slug, setSlug] = useState('')
  const [featuredImage, setFeaturedImage] = useState<string | null>(null)
  const [scheduledAt, setScheduledAt] = useState('')
  const [showSchedule, setShowSchedule] = useState(false)
  const [smartNotice, setSmartNotice] = useState<string | null>(null)
  const [prefilledPrompt, setPrefilledPrompt] = useState('')
  const [autoGenerate, setAutoGenerate] = useState(false)
  const [showRecovery, setShowRecovery] = useState(false)
  const [recoveryData, setRecoveryData] = useState<{ title: string; subtitle: string; content: Record<string, unknown>; categoryId: string } | null>(null)
  const editorRef = useRef<unknown>(null)
  const autoSaveTimer = useRef<ReturnType<typeof setTimeout> | null>(null)
  const articleIdRef = useRef<string | null>(null)

  function slugify(text: string): string {
    return text.toLowerCase().replace(/[čć]/g, 'c').replace(/[š]/g, 's').replace(/[ž]/g, 'z')
      .replace(/[đ]/g, 'dj').replace(/[^\w\s-]/g, '').replace(/\s+/g, '-').replace(/-+/g, '-').trim().slice(0, 100)
  }

  // Load site & categories
  useEffect(() => {
    fetch('/api/site').then((r) => r.json() as Promise<{ id?: string; categories?: Array<{ id: string; name: string; slug?: string; icon?: string }> }>).then((data) => {
      if (data.id) {
        setSiteId(data.id)
        const cats = data.categories || []
        setCategories(cats)
        const eventType = searchParams.get('eventType')
        if (eventType) {
          const targetSlug = EVENT_TO_CATEGORY[eventType]
          if (targetSlug) {
            const match = cats.find((c: { slug?: string }) => c.slug === targetSlug)
            if (match) setCategoryId(match.id)
          }
        }
      }
    }).catch(console.error)
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  // Handle pre-filled content from Newsroom/Calendar
  useEffect(() => {
    if (searchParams.get('smartGenerate') === 'true') {
      try {
        const raw = sessionStorage.getItem('smartArticle')
        if (raw) {
          const data = JSON.parse(raw)
          if (data.title) setTitle(data.title)
          if (data.tiptapContent) { setContent(data.tiptapContent); setInitialContent(data.tiptapContent) }
          if (data.model) setAiResult({ model: data.model, tokensIn: data.tokensIn, tokensOut: data.tokensOut })
          setSmartNotice('Article generated by AI — review and edit before publishing')
          setTimeout(() => setSmartNotice(null), 6000)
          sessionStorage.removeItem('smartArticle')
        }
      } catch {}
      return
    }

    if (searchParams.get('mode') === 'rewrite') {
      try {
        const raw = sessionStorage.getItem('diurna_rewrite_source')
        if (raw) {
          const data = JSON.parse(raw)
          sessionStorage.removeItem('diurna_rewrite_source')
          setPrefilledPrompt(`Rewrite: ${data.title}`)
          setShowAI(true)
          runAutoGenerate(data, 'rewrite')
        }
      } catch {}
      return
    }

    if (searchParams.get('mode') === 'headline-only') {
      try {
        const raw = sessionStorage.getItem('diurna_headline_only')
        if (raw) {
          const data = JSON.parse(raw)
          sessionStorage.removeItem('diurna_headline_only')
          setPrefilledPrompt(`Headline: ${data.title}`)
          setShowAI(true)
          runAutoGenerate(data, 'headline-only')
        }
      } catch {}
      return
    }

    if (searchParams.get('mode') === 'combined') {
      try {
        const raw = sessionStorage.getItem('diurna_combined_sources')
        if (raw) {
          const sources = JSON.parse(raw)
          sessionStorage.removeItem('diurna_combined_sources')
          if (sources.length > 0) {
            setPrefilledPrompt(`Combined from ${sources.length} sources`)
            setShowAI(true)
            runCombinedGenerate(sources)
          }
        }
      } catch {}
      return
    }

    if (searchParams.get('clusterId') && searchParams.get('title')) {
      const clusterTitle = searchParams.get('title') || ''
      const clusterSummary = searchParams.get('summary') || ''
      setTitle(clusterTitle)
      setPrefilledPrompt(`Write an article about: ${clusterTitle}${clusterSummary ? `\n\nContext: ${clusterSummary}` : ''}`)
      setShowAI(true)
      return
    }

    const promptParam = searchParams.get('prompt')
    if (promptParam) {
      setPrefilledPrompt(promptParam)
      setShowAI(true)
      setAutoGenerate(true)
      return
    }

    // Check localStorage but PROMPT user instead of silently restoring
    try {
      const backup = localStorage.getItem('diurna_editor_backup')
      if (backup) {
        const data = JSON.parse(backup)
        if (data.timestamp && Date.now() - data.timestamp < 3600000 && data.title) {
          setRecoveryData(data)
          setShowRecovery(true)
        }
      }
    } catch {}
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  function applyRecovery() {
    if (!recoveryData) return
    setTitle(recoveryData.title)
    setSubtitle(recoveryData.subtitle || '')
    if (recoveryData.content && Object.keys(recoveryData.content).length > 0) {
      setContent(recoveryData.content)
      setInitialContent(recoveryData.content)
    }
    if (recoveryData.categoryId) setCategoryId(recoveryData.categoryId)
    setShowRecovery(false)
    setRecoveryData(null)
  }

  function discardRecovery() {
    localStorage.removeItem('diurna_editor_backup')
    setShowRecovery(false)
    setRecoveryData(null)
  }

  async function runAutoGenerate(data: { title: string; sourceText?: string; domain?: string }, mode: string) {
    try {
      const body: Record<string, unknown> = {
        topic: data.title, category: 'Sport',
        articleType: mode === 'headline-only' ? 'breaking' : 'report',
        mode: mode === 'rewrite' ? 'rewrite' : 'single',
      }
      if (mode === 'rewrite' && data.sourceText) {
        body.sourceContext = data.sourceText
        body.sourceDomain = data.domain
      }
      const res = await fetch('/api/ai/smart-generate', {
        method: 'POST', headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(body),
      })
      const result = await res.json() as { title?: string; tiptapContent?: Record<string, unknown>; model?: string; tokensIn?: number; tokensOut?: number }
      if (result.title) setTitle(result.title)
      if (result.tiptapContent) { setContent(result.tiptapContent); setInitialContent(result.tiptapContent) }
      setAiResult({ model: result.model, tokensIn: result.tokensIn, tokensOut: result.tokensOut })
      setSmartNotice(mode === 'rewrite' ? `Rewritten from ${data.domain || 'source'}` : 'Generated from headline — review carefully')
      setTimeout(() => setSmartNotice(null), 8000)
    } catch {
      setTitle(data.title)
    }
  }

  async function runCombinedGenerate(sources: { title: string; source: string; role: string }[]) {
    try {
      const primary = sources.find(s => s.role === 'primary')
      const res = await fetch('/api/ai/smart-generate', {
        method: 'POST', headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          topic: primary?.title || sources[0].title, category: 'Sport',
          articleType: 'report', mode: 'combined', sources,
        }),
      })
      const data = await res.json() as { title?: string; tiptapContent?: Record<string, unknown>; model?: string; tokensIn?: number; tokensOut?: number }
      if (data.title) setTitle(data.title)
      if (data.tiptapContent) { setContent(data.tiptapContent); setInitialContent(data.tiptapContent) }
      setAiResult({ model: data.model, tokensIn: data.tokensIn, tokensOut: data.tokensOut })
      setSmartNotice('Combined article generated — review before publishing')
      setTimeout(() => setSmartNotice(null), 6000)
    } catch {}
  }

  useEffect(() => {
    if (title && !slug) setSlug(slugify(title))
  }, [title, slug])

  const autoSave = useCallback(async () => {
    if (!articleIdRef.current || !title.trim() || saving) return
    try {
      await fetch(`/api/articles/${articleIdRef.current}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          title,
          content,
          featuredImage: featuredImage || null,
          subtitle: subtitle || undefined,
          slug: slug || undefined,
        }),
      })
    } catch {}
  }, [title, content, featuredImage, subtitle, slug, saving])

  useEffect(() => {
    if (autoSaveTimer.current) clearTimeout(autoSaveTimer.current)
    autoSaveTimer.current = setTimeout(autoSave, 30000)
    return () => { if (autoSaveTimer.current) clearTimeout(autoSaveTimer.current) }
  }, [autoSave])

  useEffect(() => {
    if (title || Object.keys(content).length > 0) {
      try {
        localStorage.setItem('diurna_editor_backup', JSON.stringify({ title, subtitle, content, categoryId, timestamp: Date.now() }))
      } catch {}
    }
  }, [title, subtitle, content, categoryId])

  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      if ((e.metaKey || e.ctrlKey) && e.key === 's') {
        e.preventDefault()
        handleSave('DRAFT')
      }
      if ((e.metaKey || e.ctrlKey) && e.key === 'Enter') {
        e.preventDefault()
        handleSave('PUBLISHED')
      }
    }
    document.addEventListener('keydown', handler)
    return () => document.removeEventListener('keydown', handler)
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [title, content, siteId])

  async function handleSave(status: 'DRAFT' | 'SCHEDULED' | 'PUBLISHED') {
    if (!title.trim() || !siteId) return
    setSaving(true)
    try {
      const body: Record<string, unknown> = {
        title,
        content,
        siteId,
        categoryId: categoryId || undefined,
        status,
        aiGenerated: !!aiResult,
        aiModel: aiResult?.model,
        metaTitle: metaTitle || undefined,
        metaDescription: metaDesc || undefined,
        featuredImage: featuredImage || null,
        subtitle: subtitle || undefined,
        slug: slug || undefined,
      }
      if (status === 'SCHEDULED' && scheduledAt) body.scheduledAt = scheduledAt

      if (articleIdRef.current) {
        const res = await fetch(`/api/articles/${articleIdRef.current}`, {
          method: 'PATCH', headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(body),
        })
        if (res.ok) {
          setPublishedStatus(status === 'SCHEDULED' ? 'SCHEDULED' : status === 'PUBLISHED' ? 'PUBLISHED' : 'DRAFT')
          toast.success(status === 'PUBLISHED' ? 'Objavljeno' : 'Sačuvano')
          if (sendNewsletter && status === 'PUBLISHED') {
            fetch('/api/newsletter/send', {
              method: 'POST', headers: { 'Content-Type': 'application/json' },
              body: JSON.stringify({ articleId: articleIdRef.current }),
            }).catch(() => toast.error('Newsletter slanje neuspješno'))
          }
          localStorage.removeItem('diurna_editor_backup')
          router.push('/articles')
          router.refresh()
        } else {
          toast.error('Greška pri čuvanju')
        }
      } else {
        const res = await fetch('/api/articles', {
          method: 'POST', headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(body),
        })
        if (res.ok) {
          const article = await res.json() as { id?: string }
          articleIdRef.current = article.id ?? null
          setPublishedStatus(status === 'SCHEDULED' ? 'SCHEDULED' : status === 'PUBLISHED' ? 'PUBLISHED' : 'DRAFT')
          toast.success(status === 'PUBLISHED' ? 'Objavljeno' : 'Kreirano')
          if (sendNewsletter && status === 'PUBLISHED' && article.id) {
            fetch('/api/newsletter/send', {
              method: 'POST', headers: { 'Content-Type': 'application/json' },
              body: JSON.stringify({ articleId: article.id }),
            }).catch(() => toast.error('Newsletter slanje neuspješno'))
          }
          localStorage.removeItem('diurna_editor_backup')
          router.push('/articles')
          router.refresh()
        } else {
          toast.error('Greška pri kreiranju')
        }
      }
    } catch {
      toast.error('Greška — pokušaj ponovo')
    } finally { setSaving(false) }
  }

  function handleAIGenerate(result: { title?: string; content?: Record<string, unknown>; model?: string; tokensIn?: number; tokensOut?: number }) {
    if (result.title) setTitle(result.title)
    if (result.content) { setContent(result.content); setInitialContent(result.content) }
    if (result.model) setAiResult({ model: result.model, tokensIn: result.tokensIn, tokensOut: result.tokensOut })
  }

  const statusBadgeStyle = {
    DRAFT: { background: '#fef3c7', color: '#92400e' },
    PUBLISHED: { background: '#dcfce7', color: '#166534' },
    SCHEDULED: { background: '#dbeafe', color: '#1d4ed8' },
  }[publishedStatus]

  return (
    <div className="editor-layout">
      <div className="ed-top">
        <button className="ed-back" onClick={() => router.push('/newsroom')}>← Back</button>
        <div className="ed-title-bar">
          {title || 'New Article'}
          {aiResult && <span className="badge-ai">AI</span>}
          <span
            className="badge-status"
            style={{
              fontSize: 10, fontWeight: 700, padding: '3px 8px', borderRadius: 6,
              fontFamily: 'var(--mono)', textTransform: 'uppercase', letterSpacing: '0.05em',
              ...statusBadgeStyle,
            }}
          >
            {publishedStatus.toLowerCase()}
          </span>
        </div>
        <button className="ed-btn ed-btn-secondary" onClick={() => handleSave('DRAFT')} disabled={saving || !title.trim()}>
          💾 {saving ? 'Saving...' : 'Save Draft'}
        </button>
        <button className="ed-btn ed-btn-secondary" onClick={() => setShowSchedule(true)}>📅 Schedule</button>
        <label className="ed-nl-check">
          <input type="checkbox" checked={sendNewsletter} onChange={(e) => setSendNewsletter(e.target.checked)} />
          <span>📧</span>
        </label>
        <button className="ed-btn ed-btn-primary" onClick={() => handleSave('PUBLISHED')} disabled={saving || !title.trim()}>
          ⚡ {saving ? 'Publishing...' : 'Publish'}
        </button>
      </div>

      {smartNotice && (
        <div className="ed-notice">
          <span>✨ {smartNotice}</span>
          <button onClick={() => setSmartNotice(null)}>×</button>
        </div>
      )}

      {showRecovery && recoveryData && (
        <div style={{
          background: '#fffbeb', borderBottom: '1px solid #fde68a',
          padding: '10px 20px', display: 'flex', alignItems: 'center', gap: 12,
          fontSize: 13, color: '#92400e',
        }}>
          <span>📝 You have an unsaved draft: <strong>{recoveryData.title}</strong></span>
          <button
            onClick={applyRecovery}
            style={{ padding: '4px 12px', background: '#f59e0b', color: '#fff', border: 'none', borderRadius: 6, fontWeight: 700, cursor: 'pointer', fontSize: 12 }}
          >
            Restore
          </button>
          <button
            onClick={discardRecovery}
            style={{ padding: '4px 12px', background: 'none', border: '1px solid #fde68a', borderRadius: 6, fontWeight: 600, cursor: 'pointer', fontSize: 12, color: '#92400e' }}
          >
            Discard
          </button>
        </div>
      )}

      <div className="editor-main">
        <div className="editor-left">
          <div className="ed-form">
            <input type="text" className="ed-title-input" placeholder="Naslov članka..."
              value={title} onChange={(e) => { setTitle(e.target.value); setSlug(slugify(e.target.value)) }} />
            <input type="text" className="ed-subtitle-input" placeholder="Podnaslov (opcionalno)"
              value={subtitle} onChange={(e) => setSubtitle(e.target.value)} />
            <FeaturedImagePicker value={featuredImage} onChange={setFeaturedImage} />
            <div className="ed-meta">
              <select className="ed-select" value={categoryId} onChange={(e) => setCategoryId(e.target.value)}>
                <option value="">No category</option>
                {categories.map((cat) => (
                  <option key={cat.id} value={cat.id}>{cat.icon ? `${cat.icon} ` : ''}{cat.name}</option>
                ))}
              </select>
            </div>
            <TiptapEditor
              content={initialContent && Object.keys(initialContent).length > 0 ? initialContent : undefined}
              onChange={(json) => setContent(json)}
              onEditorReady={(e) => { editorRef.current = e }}
              placeholder="Start writing your article..."
            />
          </div>

          <div className="ed-bottom">
            <button className="ed-seo-toggle" onClick={() => setShowSEO(!showSEO)}>
              {showSEO ? '▾' : '▸'} SEO Settings
            </button>
            {showSEO && (
              <div className="ed-seo-panel">
                <div className="ed-seo-field">
                  <label>Meta Title</label>
                  <input type="text" value={metaTitle} onChange={(e) => setMetaTitle(e.target.value)} placeholder={title} maxLength={60} />
                  <span className="ed-seo-count">{(metaTitle || title).length}/60</span>
                </div>
                <div className="ed-seo-field">
                  <label>Meta Description</label>
                  <textarea value={metaDesc} onChange={(e) => setMetaDesc(e.target.value)} placeholder="Article description for search engines..." maxLength={155} rows={2} />
                  <span className="ed-seo-count">{metaDesc.length}/155</span>
                </div>
                <div className="ed-seo-field">
                  <label>Slug</label>
                  <input type="text" value={slug} onChange={(e) => setSlug(slugify(e.target.value))} className="ed-slug-mono" />
                </div>
              </div>
            )}
          </div>

          {aiResult && (
            <div className="ai-result-info">
              <span>🤖 {aiResult.model}</span>
              <span>· {aiResult.tokensIn}→{aiResult.tokensOut} tokens</span>
            </div>
          )}
        </div>

        {showAI && (
          <div className="editor-right">
            <AISidebar
              editor={editorRef.current as import('@tiptap/react').Editor | null}
              onGenerate={handleAIGenerate}
              prefilledPrompt={prefilledPrompt}
              autoGenerate={autoGenerate}
            />
          </div>
        )}
      </div>

      <button className="ai-toggle-btn" onClick={() => setShowAI(!showAI)} title="Toggle AI Co-Pilot">
        {showAI ? '✕' : '🤖'} {showAI ? '' : 'AI'}
      </button>

      {showSchedule && (
        <div className="ed-modal-overlay" onClick={(e) => { if (e.target === e.currentTarget) setShowSchedule(false) }}>
          <div className="ed-modal">
            <div className="ed-modal-head">
              <div className="ed-modal-title">📅 Schedule Article</div>
              <button className="ed-modal-close" onClick={() => setShowSchedule(false)}>×</button>
            </div>
            <div className="ed-modal-body">
              <label className="ed-modal-label">Publish date and time</label>
              <input type="datetime-local" className="ed-schedule-input" value={scheduledAt}
                onChange={(e) => setScheduledAt(e.target.value)} min={new Date().toISOString().slice(0, 16)} />
              {scheduledAt && (
                <div className="ed-schedule-preview">
                  Will publish on {new Date(scheduledAt).toLocaleString('en-GB', { day: 'numeric', month: 'long', year: 'numeric', hour: '2-digit', minute: '2-digit' })}
                </div>
              )}
              <div className="ed-modal-actions">
                <button className="ed-btn ed-btn-secondary" onClick={() => { setScheduledAt(''); setShowSchedule(false) }}>Clear</button>
                <button className="ed-btn ed-btn-primary" disabled={!scheduledAt}
                  onClick={() => { handleSave('SCHEDULED'); setShowSchedule(false) }}>📅 Schedule</button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
