import { prisma } from '@/lib/prisma'
import { Prisma } from '@prisma/client'
import { NextResponse } from 'next/server'

const ENTITIES: { name: string; type: string; aliases: string[]; metadata?: Record<string, unknown> }[] = [
  { name: 'Erling Haaland', type: 'PLAYER', aliases: ['Haaland', 'Erling Haaland'], metadata: { club: 'Manchester City', country: 'Norway', position: 'ST' } },
  { name: 'Mohamed Salah', type: 'PLAYER', aliases: ['Salah', 'Mo Salah', 'Mohamed Salah'], metadata: { club: 'Liverpool', country: 'Egypt', position: 'RW' } },
  { name: 'Bukayo Saka', type: 'PLAYER', aliases: ['Saka', 'Bukayo Saka'], metadata: { club: 'Arsenal', country: 'England', position: 'RW' } },
  { name: 'Marcus Rashford', type: 'PLAYER', aliases: ['Rashford', 'Marcus Rashford'], metadata: { club: 'Manchester United', country: 'England', position: 'LW' } },
  { name: 'Bruno Fernandes', type: 'PLAYER', aliases: ['Bruno Fernandes', 'Bruno'], metadata: { club: 'Manchester United', country: 'Portugal', position: 'CAM' } },
  { name: 'Cole Palmer', type: 'PLAYER', aliases: ['Palmer', 'Cole Palmer'], metadata: { club: 'Chelsea', country: 'England', position: 'CAM' } },
  { name: 'Martin Odegaard', type: 'PLAYER', aliases: ['Odegaard', 'Martin Odegaard', 'Ødegaard'], metadata: { club: 'Arsenal', country: 'Norway', position: 'CAM' } },
  { name: 'Son Heung-min', type: 'PLAYER', aliases: ['Son', 'Heung-min Son', 'Son Heung-min', 'Sonny'], metadata: { club: 'Tottenham', country: 'South Korea', position: 'LW' } },
  { name: 'Kevin De Bruyne', type: 'PLAYER', aliases: ['De Bruyne', 'Kevin De Bruyne', 'KDB'], metadata: { club: 'Manchester City', country: 'Belgium', position: 'CAM' } },
  { name: 'Phil Foden', type: 'PLAYER', aliases: ['Foden', 'Phil Foden'], metadata: { club: 'Manchester City', country: 'England', position: 'LW' } },
  { name: 'Declan Rice', type: 'PLAYER', aliases: ['Rice', 'Declan Rice'], metadata: { club: 'Arsenal', country: 'England', position: 'CDM' } },
  { name: 'Alexander Isak', type: 'PLAYER', aliases: ['Isak', 'Alexander Isak'], metadata: { club: 'Newcastle', country: 'Sweden', position: 'ST' } },
  { name: 'Virgil van Dijk', type: 'PLAYER', aliases: ['Van Dijk', 'Virgil van Dijk', 'VVD'], metadata: { club: 'Liverpool', country: 'Netherlands', position: 'CB' } },
  { name: 'Alexis Mac Allister', type: 'PLAYER', aliases: ['Mac Allister', 'Alexis Mac Allister', 'MacAllister'], metadata: { club: 'Liverpool', country: 'Argentina', position: 'CM' } },
  { name: 'Matthijs de Ligt', type: 'PLAYER', aliases: ['De Ligt', 'Matthijs de Ligt', 'de Ligt'], metadata: { club: 'Manchester United', country: 'Netherlands', position: 'CB' } },
  { name: 'Harry Maguire', type: 'PLAYER', aliases: ['Maguire', 'Harry Maguire'], metadata: { club: 'Manchester United', country: 'England', position: 'CB' } },
  { name: 'Sandro Tonali', type: 'PLAYER', aliases: ['Tonali', 'Sandro Tonali'], metadata: { club: 'Newcastle', country: 'Italy', position: 'CM' } },
  { name: 'Ollie Watkins', type: 'PLAYER', aliases: ['Watkins', 'Ollie Watkins'], metadata: { club: 'Aston Villa', country: 'England', position: 'ST' } },
  { name: 'James Maddison', type: 'PLAYER', aliases: ['Maddison', 'James Maddison'], metadata: { club: 'Tottenham', country: 'England', position: 'CAM' } },
  { name: 'Trent Alexander-Arnold', type: 'PLAYER', aliases: ['Trent', 'Alexander-Arnold', 'TAA', 'Trent Alexander-Arnold'], metadata: { club: 'Liverpool', country: 'England', position: 'RB' } },
  { name: 'Kylian Mbappe', type: 'PLAYER', aliases: ['Mbappe', 'Kylian Mbappe', 'Mbappé'], metadata: { club: 'Real Madrid', country: 'France', position: 'LW' } },
  { name: 'Vinicius Junior', type: 'PLAYER', aliases: ['Vinicius', 'Vinicius Jr', 'Vini Jr', 'Vinicius Junior'], metadata: { club: 'Real Madrid', country: 'Brazil', position: 'LW' } },
  { name: 'Jude Bellingham', type: 'PLAYER', aliases: ['Bellingham', 'Jude Bellingham'], metadata: { club: 'Real Madrid', country: 'England', position: 'CAM' } },
  { name: 'Lamine Yamal', type: 'PLAYER', aliases: ['Yamal', 'Lamine Yamal'], metadata: { club: 'Barcelona', country: 'Spain', position: 'RW' } },
  { name: 'Robert Lewandowski', type: 'PLAYER', aliases: ['Lewandowski', 'Robert Lewandowski', 'Lewy'], metadata: { club: 'Barcelona', country: 'Poland', position: 'ST' } },
  { name: 'Pedri', type: 'PLAYER', aliases: ['Pedri', 'Pedro Gonzalez'], metadata: { club: 'Barcelona', country: 'Spain', position: 'CM' } },
  { name: 'Gavi', type: 'PLAYER', aliases: ['Gavi', 'Pablo Gavi'], metadata: { club: 'Barcelona', country: 'Spain', position: 'CM' } },
  { name: 'Raphinha', type: 'PLAYER', aliases: ['Raphinha'], metadata: { club: 'Barcelona', country: 'Brazil', position: 'RW' } },
  { name: 'Rodrygo', type: 'PLAYER', aliases: ['Rodrygo', 'Rodrygo Goes'], metadata: { club: 'Real Madrid', country: 'Brazil', position: 'RW' } },
  { name: 'Federico Valverde', type: 'PLAYER', aliases: ['Valverde', 'Fede Valverde', 'Federico Valverde'], metadata: { club: 'Real Madrid', country: 'Uruguay', position: 'CM' } },
  { name: 'Antoine Griezmann', type: 'PLAYER', aliases: ['Griezmann', 'Antoine Griezmann'], metadata: { club: 'Atletico Madrid', country: 'France', position: 'ST' } },
  { name: 'Lautaro Martinez', type: 'PLAYER', aliases: ['Lautaro', 'Lautaro Martinez', 'Lautaro Martínez'], metadata: { club: 'Inter Milan', country: 'Argentina', position: 'ST' } },
  { name: 'Victor Osimhen', type: 'PLAYER', aliases: ['Osimhen', 'Victor Osimhen'], metadata: { club: 'Napoli', country: 'Nigeria', position: 'ST' } },
  { name: 'Rafael Leao', type: 'PLAYER', aliases: ['Leao', 'Rafael Leao', 'Leão'], metadata: { club: 'AC Milan', country: 'Portugal', position: 'LW' } },
  { name: 'Dusan Vlahovic', type: 'PLAYER', aliases: ['Vlahovic', 'Dusan Vlahovic', 'Vlahović'], metadata: { club: 'Juventus', country: 'Serbia', position: 'ST' } },
  { name: 'Khvicha Kvaratskhelia', type: 'PLAYER', aliases: ['Kvaratskhelia', 'Kvara', 'Khvicha'], metadata: { club: 'PSG', country: 'Georgia', position: 'LW' } },
  { name: 'Florian Wirtz', type: 'PLAYER', aliases: ['Wirtz', 'Florian Wirtz'], metadata: { club: 'Bayer Leverkusen', country: 'Germany', position: 'CAM' } },
  { name: 'Jamal Musiala', type: 'PLAYER', aliases: ['Musiala', 'Jamal Musiala'], metadata: { club: 'Bayern Munich', country: 'Germany', position: 'CAM' } },
  { name: 'Harry Kane', type: 'PLAYER', aliases: ['Kane', 'Harry Kane'], metadata: { club: 'Bayern Munich', country: 'England', position: 'ST' } },
  { name: 'Leroy Sane', type: 'PLAYER', aliases: ['Sane', 'Leroy Sane', 'Sané'], metadata: { club: 'Bayern Munich', country: 'Germany', position: 'RW' } },
  { name: 'Ousmane Dembele', type: 'PLAYER', aliases: ['Dembele', 'Ousmane Dembele', 'Dembélé'], metadata: { club: 'PSG', country: 'France', position: 'RW' } },
  { name: 'Bradley Barcola', type: 'PLAYER', aliases: ['Barcola', 'Bradley Barcola'], metadata: { club: 'PSG', country: 'France', position: 'LW' } },
  { name: 'Cristiano Ronaldo', type: 'PLAYER', aliases: ['Ronaldo', 'Cristiano Ronaldo', 'CR7', 'Cristiano'], metadata: { club: 'Al Nassr', country: 'Portugal', position: 'ST' } },
  { name: 'Lionel Messi', type: 'PLAYER', aliases: ['Messi', 'Lionel Messi', 'Leo Messi'], metadata: { club: 'Inter Miami', country: 'Argentina', position: 'RW' } },
  { name: 'Neymar', type: 'PLAYER', aliases: ['Neymar', 'Neymar Jr', 'Neymar Junior'], metadata: { club: 'Santos', country: 'Brazil', position: 'LW' } },
  { name: 'Viktor Gyokeres', type: 'PLAYER', aliases: ['Gyokeres', 'Viktor Gyokeres', 'Gyökeres'], metadata: { club: 'Sporting CP', country: 'Sweden', position: 'ST' } },
  { name: 'Nico Williams', type: 'PLAYER', aliases: ['Nico Williams'], metadata: { club: 'Athletic Bilbao', country: 'Spain', position: 'LW' } },
  { name: 'Joao Neves', type: 'PLAYER', aliases: ['Joao Neves', 'João Neves'], metadata: { club: 'PSG', country: 'Portugal', position: 'CM' } },
  { name: 'Manchester United', type: 'CLUB', aliases: ['Manchester United', 'Man United', 'Man Utd', 'MUFC'], metadata: { league: 'Premier League', country: 'England', stadium: 'Old Trafford' } },
  { name: 'Manchester City', type: 'CLUB', aliases: ['Manchester City', 'Man City', 'MCFC'], metadata: { league: 'Premier League', country: 'England', stadium: 'Etihad Stadium' } },
  { name: 'Liverpool', type: 'CLUB', aliases: ['Liverpool', 'Liverpool FC', 'LFC'], metadata: { league: 'Premier League', country: 'England', stadium: 'Anfield' } },
  { name: 'Arsenal', type: 'CLUB', aliases: ['Arsenal', 'Arsenal FC', 'Gunners'], metadata: { league: 'Premier League', country: 'England', stadium: 'Emirates Stadium' } },
  { name: 'Chelsea', type: 'CLUB', aliases: ['Chelsea', 'Chelsea FC', 'Blues'], metadata: { league: 'Premier League', country: 'England', stadium: 'Stamford Bridge' } },
  { name: 'Tottenham Hotspur', type: 'CLUB', aliases: ['Tottenham', 'Spurs', 'Tottenham Hotspur'], metadata: { league: 'Premier League', country: 'England' } },
  { name: 'Newcastle United', type: 'CLUB', aliases: ['Newcastle', 'Newcastle United', 'NUFC', 'Magpies'], metadata: { league: 'Premier League', country: 'England' } },
  { name: 'Aston Villa', type: 'CLUB', aliases: ['Aston Villa', 'Villa', 'AVFC'], metadata: { league: 'Premier League', country: 'England' } },
  { name: 'Brighton', type: 'CLUB', aliases: ['Brighton', 'Brighton & Hove Albion', 'Brighton and Hove'], metadata: { league: 'Premier League', country: 'England' } },
  { name: 'West Ham United', type: 'CLUB', aliases: ['West Ham', 'West Ham United', 'Hammers'], metadata: { league: 'Premier League', country: 'England' } },
  { name: 'Crystal Palace', type: 'CLUB', aliases: ['Crystal Palace', 'Palace'], metadata: { league: 'Premier League', country: 'England' } },
  { name: 'Wolverhampton', type: 'CLUB', aliases: ['Wolves', 'Wolverhampton', 'Wolverhampton Wanderers'], metadata: { league: 'Premier League', country: 'England' } },
  { name: 'Everton', type: 'CLUB', aliases: ['Everton', 'Everton FC', 'Toffees'], metadata: { league: 'Premier League', country: 'England' } },
  { name: 'Nottingham Forest', type: 'CLUB', aliases: ['Nottingham Forest', 'Forest', 'Nott Forest'], metadata: { league: 'Premier League', country: 'England' } },
  { name: 'Fulham', type: 'CLUB', aliases: ['Fulham', 'Fulham FC'], metadata: { league: 'Premier League', country: 'England' } },
  { name: 'Bournemouth', type: 'CLUB', aliases: ['Bournemouth', 'AFC Bournemouth'], metadata: { league: 'Premier League', country: 'England' } },
  { name: 'Brentford', type: 'CLUB', aliases: ['Brentford', 'Brentford FC'], metadata: { league: 'Premier League', country: 'England' } },
  { name: 'Ipswich Town', type: 'CLUB', aliases: ['Ipswich', 'Ipswich Town'], metadata: { league: 'Premier League', country: 'England' } },
  { name: 'Leicester City', type: 'CLUB', aliases: ['Leicester', 'Leicester City', 'Foxes'], metadata: { league: 'Premier League', country: 'England' } },
  { name: 'Southampton', type: 'CLUB', aliases: ['Southampton', 'Saints'], metadata: { league: 'Premier League', country: 'England' } },
  { name: 'Real Madrid', type: 'CLUB', aliases: ['Real Madrid', 'Madrid', 'Los Blancos'], metadata: { league: 'La Liga', country: 'Spain', stadium: 'Santiago Bernabeu' } },
  { name: 'Barcelona', type: 'CLUB', aliases: ['Barcelona', 'Barca', 'FC Barcelona', 'Barça'], metadata: { league: 'La Liga', country: 'Spain', stadium: 'Camp Nou' } },
  { name: 'Atletico Madrid', type: 'CLUB', aliases: ['Atletico Madrid', 'Atletico', 'Atlético Madrid', 'Atleti'], metadata: { league: 'La Liga', country: 'Spain' } },
  { name: 'Real Sociedad', type: 'CLUB', aliases: ['Real Sociedad', 'Sociedad', 'La Real'], metadata: { league: 'La Liga', country: 'Spain' } },
  { name: 'Real Betis', type: 'CLUB', aliases: ['Real Betis', 'Betis'], metadata: { league: 'La Liga', country: 'Spain' } },
  { name: 'Sevilla', type: 'CLUB', aliases: ['Sevilla', 'Sevilla FC'], metadata: { league: 'La Liga', country: 'Spain' } },
  { name: 'Villarreal', type: 'CLUB', aliases: ['Villarreal', 'Yellow Submarine'], metadata: { league: 'La Liga', country: 'Spain' } },
  { name: 'Athletic Bilbao', type: 'CLUB', aliases: ['Athletic Bilbao', 'Athletic Club', 'Bilbao'], metadata: { league: 'La Liga', country: 'Spain' } },
  { name: 'Girona', type: 'CLUB', aliases: ['Girona', 'Girona FC'], metadata: { league: 'La Liga', country: 'Spain' } },
  { name: 'Juventus', type: 'CLUB', aliases: ['Juventus', 'Juve', 'Juventus FC'], metadata: { league: 'Serie A', country: 'Italy' } },
  { name: 'Inter Milan', type: 'CLUB', aliases: ['Inter Milan', 'Inter', 'Internazionale', 'FC Inter'], metadata: { league: 'Serie A', country: 'Italy' } },
  { name: 'AC Milan', type: 'CLUB', aliases: ['AC Milan', 'Milan', 'Rossoneri'], metadata: { league: 'Serie A', country: 'Italy' } },
  { name: 'Napoli', type: 'CLUB', aliases: ['Napoli', 'SSC Napoli'], metadata: { league: 'Serie A', country: 'Italy' } },
  { name: 'Roma', type: 'CLUB', aliases: ['Roma', 'AS Roma'], metadata: { league: 'Serie A', country: 'Italy' } },
  { name: 'Lazio', type: 'CLUB', aliases: ['Lazio', 'SS Lazio'], metadata: { league: 'Serie A', country: 'Italy' } },
  { name: 'Atalanta', type: 'CLUB', aliases: ['Atalanta', 'Atalanta BC'], metadata: { league: 'Serie A', country: 'Italy' } },
  { name: 'Fiorentina', type: 'CLUB', aliases: ['Fiorentina', 'ACF Fiorentina', 'Viola'], metadata: { league: 'Serie A', country: 'Italy' } },
  { name: 'Bayern Munich', type: 'CLUB', aliases: ['Bayern Munich', 'Bayern', 'FC Bayern', 'Bayern München'], metadata: { league: 'Bundesliga', country: 'Germany' } },
  { name: 'Borussia Dortmund', type: 'CLUB', aliases: ['Borussia Dortmund', 'Dortmund', 'BVB'], metadata: { league: 'Bundesliga', country: 'Germany' } },
  { name: 'Bayer Leverkusen', type: 'CLUB', aliases: ['Bayer Leverkusen', 'Leverkusen'], metadata: { league: 'Bundesliga', country: 'Germany' } },
  { name: 'RB Leipzig', type: 'CLUB', aliases: ['RB Leipzig', 'Leipzig'], metadata: { league: 'Bundesliga', country: 'Germany' } },
  { name: 'Paris Saint-Germain', type: 'CLUB', aliases: ['Paris Saint-Germain', 'PSG', 'Paris SG'], metadata: { league: 'Ligue 1', country: 'France' } },
  { name: 'Marseille', type: 'CLUB', aliases: ['Marseille', 'Olympique Marseille', 'OM'], metadata: { league: 'Ligue 1', country: 'France' } },
  { name: 'Lyon', type: 'CLUB', aliases: ['Lyon', 'Olympique Lyonnais', 'OL'], metadata: { league: 'Ligue 1', country: 'France' } },
  { name: 'Monaco', type: 'CLUB', aliases: ['Monaco', 'AS Monaco'], metadata: { league: 'Ligue 1', country: 'France' } },
  { name: 'Sporting CP', type: 'CLUB', aliases: ['Sporting CP', 'Sporting Lisbon', 'Sporting'], metadata: { league: 'Liga Portugal', country: 'Portugal' } },
  { name: 'Benfica', type: 'CLUB', aliases: ['Benfica', 'SL Benfica'], metadata: { league: 'Liga Portugal', country: 'Portugal' } },
  { name: 'Porto', type: 'CLUB', aliases: ['Porto', 'FC Porto'], metadata: { league: 'Liga Portugal', country: 'Portugal' } },
  { name: 'Ajax', type: 'CLUB', aliases: ['Ajax', 'AFC Ajax', 'Ajax Amsterdam'], metadata: { league: 'Eredivisie', country: 'Netherlands' } },
  { name: 'Celtic', type: 'CLUB', aliases: ['Celtic', 'Celtic FC', 'Glasgow Celtic'], metadata: { league: 'SPL', country: 'Scotland' } },
  { name: 'Rangers', type: 'CLUB', aliases: ['Rangers', 'Rangers FC', 'Glasgow Rangers'], metadata: { league: 'SPL', country: 'Scotland' } },
  { name: 'Galatasaray', type: 'CLUB', aliases: ['Galatasaray', 'Gala'], metadata: { league: 'Super Lig', country: 'Turkey' } },
  { name: 'Fenerbahce', type: 'CLUB', aliases: ['Fenerbahce', 'Fenerbahçe', 'Fener'], metadata: { league: 'Super Lig', country: 'Turkey' } },
  { name: 'Pep Guardiola', type: 'MANAGER', aliases: ['Guardiola', 'Pep Guardiola', 'Pep'], metadata: { club: 'Manchester City', country: 'Spain' } },
  { name: 'Jurgen Klopp', type: 'MANAGER', aliases: ['Klopp', 'Jurgen Klopp', 'Jürgen Klopp'], metadata: { club: 'Free Agent', country: 'Germany' } },
  { name: 'Mikel Arteta', type: 'MANAGER', aliases: ['Arteta', 'Mikel Arteta'], metadata: { club: 'Arsenal', country: 'Spain' } },
  { name: 'Arne Slot', type: 'MANAGER', aliases: ['Slot', 'Arne Slot'], metadata: { club: 'Liverpool', country: 'Netherlands' } },
  { name: 'Erik ten Hag', type: 'MANAGER', aliases: ['Ten Hag', 'Erik ten Hag', 'ETH'], metadata: { club: 'Free Agent', country: 'Netherlands' } },
  { name: 'Ruben Amorim', type: 'MANAGER', aliases: ['Amorim', 'Ruben Amorim', 'Rúben Amorim'], metadata: { club: 'Manchester United', country: 'Portugal' } },
  { name: 'Carlo Ancelotti', type: 'MANAGER', aliases: ['Ancelotti', 'Carlo Ancelotti'], metadata: { club: 'Real Madrid', country: 'Italy' } },
  { name: 'Hansi Flick', type: 'MANAGER', aliases: ['Flick', 'Hansi Flick'], metadata: { club: 'Barcelona', country: 'Germany' } },
  { name: 'Diego Simeone', type: 'MANAGER', aliases: ['Simeone', 'Diego Simeone', 'Cholo'], metadata: { club: 'Atletico Madrid', country: 'Argentina' } },
  { name: 'Enzo Maresca', type: 'MANAGER', aliases: ['Maresca', 'Enzo Maresca'], metadata: { club: 'Chelsea', country: 'Italy' } },
  { name: 'Unai Emery', type: 'MANAGER', aliases: ['Emery', 'Unai Emery'], metadata: { club: 'Aston Villa', country: 'Spain' } },
  { name: 'Simone Inzaghi', type: 'MANAGER', aliases: ['Inzaghi', 'Simone Inzaghi'], metadata: { club: 'Inter Milan', country: 'Italy' } },
  { name: 'Thiago Motta', type: 'MANAGER', aliases: ['Thiago Motta'], metadata: { club: 'Juventus', country: 'Italy' } },
  { name: 'Xabi Alonso', type: 'MANAGER', aliases: ['Xabi Alonso', 'Alonso'], metadata: { club: 'Bayer Leverkusen', country: 'Spain' } },
  { name: 'Vincent Kompany', type: 'MANAGER', aliases: ['Kompany', 'Vincent Kompany'], metadata: { club: 'Bayern Munich', country: 'Belgium' } },
  { name: 'Luis Enrique', type: 'MANAGER', aliases: ['Luis Enrique', 'Lucho'], metadata: { club: 'PSG', country: 'Spain' } },
  { name: 'Antonio Conte', type: 'MANAGER', aliases: ['Conte', 'Antonio Conte'], metadata: { club: 'Napoli', country: 'Italy' } },
  { name: 'Jose Mourinho', type: 'MANAGER', aliases: ['Mourinho', 'Jose Mourinho', 'José Mourinho', 'The Special One'], metadata: { club: 'Fenerbahce', country: 'Portugal' } },
  { name: 'Zinedine Zidane', type: 'MANAGER', aliases: ['Zidane', 'Zinedine Zidane', 'Zizou'], metadata: { club: 'Free Agent', country: 'France' } },
  { name: 'Mauricio Pochettino', type: 'MANAGER', aliases: ['Pochettino', 'Poch', 'Mauricio Pochettino'], metadata: { club: 'USMNT', country: 'Argentina' } },
  { name: 'Nuno Espirito Santo', type: 'MANAGER', aliases: ['Nuno', 'Nuno Espirito Santo'], metadata: { club: 'Nottingham Forest', country: 'Portugal' } },
  { name: 'Premier League', type: 'LEAGUE', aliases: ['Premier League', 'EPL', 'English Premier League', 'PL'] },
  { name: 'La Liga', type: 'LEAGUE', aliases: ['La Liga', 'LaLiga', 'Spanish League', 'Liga'] },
  { name: 'Serie A', type: 'LEAGUE', aliases: ['Serie A', 'Italian Serie A', 'Calcio'] },
  { name: 'Bundesliga', type: 'LEAGUE', aliases: ['Bundesliga', 'German Bundesliga'] },
  { name: 'Ligue 1', type: 'LEAGUE', aliases: ['Ligue 1', 'Ligue One', 'French League'] },
  { name: 'Eredivisie', type: 'LEAGUE', aliases: ['Eredivisie', 'Dutch League'] },
  { name: 'Liga Portugal', type: 'LEAGUE', aliases: ['Liga Portugal', 'Primeira Liga', 'Portuguese League'] },
  { name: 'Scottish Premiership', type: 'LEAGUE', aliases: ['Scottish Premiership', 'SPL', 'SPFL'] },
  { name: 'Championship', type: 'LEAGUE', aliases: ['Championship', 'EFL Championship', 'English Championship'] },
  { name: 'Super Lig', type: 'LEAGUE', aliases: ['Super Lig', 'Turkish Super Lig', 'Süper Lig'] },
  { name: 'Saudi Pro League', type: 'LEAGUE', aliases: ['Saudi Pro League', 'SPL Saudi', 'Roshn Saudi League'] },
  { name: 'MLS', type: 'LEAGUE', aliases: ['MLS', 'Major League Soccer'] },
  { name: 'Champions League', type: 'COMPETITION', aliases: ['Champions League', 'UCL', 'CL', 'UEFA Champions League'] },
  { name: 'Europa League', type: 'COMPETITION', aliases: ['Europa League', 'UEL', 'UEFA Europa League'] },
  { name: 'Conference League', type: 'COMPETITION', aliases: ['Conference League', 'UECL', 'Europa Conference League'] },
  { name: 'FA Cup', type: 'COMPETITION', aliases: ['FA Cup', 'Emirates FA Cup'] },
  { name: 'League Cup', type: 'COMPETITION', aliases: ['League Cup', 'Carabao Cup', 'EFL Cup'] },
  { name: 'Copa del Rey', type: 'COMPETITION', aliases: ['Copa del Rey', 'Spanish Cup'] },
  { name: 'Coppa Italia', type: 'COMPETITION', aliases: ['Coppa Italia', 'Italian Cup'] },
  { name: 'DFB Pokal', type: 'COMPETITION', aliases: ['DFB Pokal', 'DFB-Pokal', 'German Cup'] },
  { name: 'Coupe de France', type: 'COMPETITION', aliases: ['Coupe de France', 'French Cup'] },
  { name: 'World Cup', type: 'COMPETITION', aliases: ['World Cup', 'FIFA World Cup', 'WC'] },
  { name: 'European Championship', type: 'COMPETITION', aliases: ['European Championship', 'Euros', 'Euro', 'UEFA Euro'] },
  { name: 'Copa America', type: 'COMPETITION', aliases: ['Copa America', 'Copa América'] },
  { name: 'Africa Cup of Nations', type: 'COMPETITION', aliases: ['AFCON', 'Africa Cup of Nations', 'African Cup'] },
  { name: 'Club World Cup', type: 'COMPETITION', aliases: ['Club World Cup', 'FIFA Club World Cup', 'CWC'] },
  { name: 'Super Cup', type: 'COMPETITION', aliases: ['Super Cup', 'UEFA Super Cup'] },
  { name: 'Community Shield', type: 'COMPETITION', aliases: ['Community Shield', 'FA Community Shield'] },
  { name: 'El Clasico', type: 'COMPETITION', aliases: ['El Clasico', 'El Clásico', 'Clasico'], metadata: { clubs: ['Real Madrid', 'Barcelona'] } },
  { name: 'Manchester Derby', type: 'COMPETITION', aliases: ['Manchester Derby', 'Manchester derby'], metadata: { clubs: ['Manchester United', 'Manchester City'] } },
  { name: 'North London Derby', type: 'COMPETITION', aliases: ['North London Derby', 'NLD'], metadata: { clubs: ['Arsenal', 'Tottenham'] } },
  { name: 'Merseyside Derby', type: 'COMPETITION', aliases: ['Merseyside Derby'], metadata: { clubs: ['Liverpool', 'Everton'] } },
  { name: 'Fabrizio Romano', type: 'JOURNALIST', aliases: ['Fabrizio Romano', 'Romano', 'Here we go'], metadata: { specialty: 'transfers' } },
  { name: 'David Ornstein', type: 'JOURNALIST', aliases: ['David Ornstein', 'Ornstein'], metadata: { specialty: 'transfers', outlet: 'The Athletic' } },
  { name: 'Gianluca Di Marzio', type: 'JOURNALIST', aliases: ['Di Marzio', 'Gianluca Di Marzio'], metadata: { specialty: 'transfers', outlet: 'Sky Italia' } },
]

export async function POST() {
  let created = 0

  for (const entity of ENTITIES) {
    try {
      await prisma.entity.upsert({
        where: { name: entity.name },
        update: {
          type: entity.type,
          aliases: entity.aliases,
          metadata: (entity.metadata || {}) as Prisma.InputJsonValue,
        },
        create: {
          name: entity.name,
          type: entity.type,
          aliases: entity.aliases,
          metadata: (entity.metadata || {}) as Prisma.InputJsonValue,
        },
      })
      created++
    } catch {}
  }

  return NextResponse.json({
    created,
    total: ENTITIES.length,
    breakdown: {
      players: ENTITIES.filter(e => e.type === 'PLAYER').length,
      clubs: ENTITIES.filter(e => e.type === 'CLUB').length,
      managers: ENTITIES.filter(e => e.type === 'MANAGER').length,
      leagues: ENTITIES.filter(e => e.type === 'LEAGUE').length,
      competitions: ENTITIES.filter(e => e.type === 'COMPETITION').length,
      journalists: ENTITIES.filter(e => e.type === 'JOURNALIST').length,
    },
  })
}
