import { prisma } from '@/lib/prisma'
import { Prisma } from '@prisma/client'
import { NextResponse } from 'next/server'

type EntityDef = { name: string; type: string; aliases: string[]; metadata?: Record<string, unknown> }

const PLAYERS: EntityDef[] = [
  { name: 'Erling Haaland', type: 'PLAYER', aliases: ['Haaland', 'Erling'], metadata: { team: 'Manchester City', position: 'ST', nationality: 'Norway' } },
  { name: 'Mohamed Salah', type: 'PLAYER', aliases: ['Salah', 'Mo Salah'], metadata: { team: 'Liverpool', position: 'RW', nationality: 'Egypt' } },
  { name: 'Bukayo Saka', type: 'PLAYER', aliases: ['Saka'], metadata: { team: 'Arsenal', position: 'RW', nationality: 'England' } },
  { name: 'Cole Palmer', type: 'PLAYER', aliases: ['Palmer'], metadata: { team: 'Chelsea', position: 'AM', nationality: 'England' } },
  { name: 'Marcus Rashford', type: 'PLAYER', aliases: ['Rashford'], metadata: { team: 'Manchester United', position: 'LW', nationality: 'England' } },
  { name: 'Bruno Fernandes', type: 'PLAYER', aliases: ['Bruno', 'B. Fernandes'], metadata: { team: 'Manchester United', position: 'AM', nationality: 'Portugal' } },
  { name: 'Martin Odegaard', type: 'PLAYER', aliases: ['Odegaard', 'Ødegaard'], metadata: { team: 'Arsenal', position: 'AM', nationality: 'Norway' } },
  { name: 'Phil Foden', type: 'PLAYER', aliases: ['Foden'], metadata: { team: 'Manchester City', position: 'AM', nationality: 'England' } },
  { name: 'Son Heung-min', type: 'PLAYER', aliases: ['Son', 'Heung-min Son', 'Sonny'], metadata: { team: 'Tottenham', position: 'LW', nationality: 'South Korea' } },
  { name: 'Kevin De Bruyne', type: 'PLAYER', aliases: ['De Bruyne', 'KDB'], metadata: { team: 'Manchester City', position: 'CM', nationality: 'Belgium' } },
  { name: 'Alexander Isak', type: 'PLAYER', aliases: ['Isak'], metadata: { team: 'Newcastle', position: 'ST', nationality: 'Sweden' } },
  { name: 'Declan Rice', type: 'PLAYER', aliases: ['Rice'], metadata: { team: 'Arsenal', position: 'CM', nationality: 'England' } },
  { name: 'Virgil van Dijk', type: 'PLAYER', aliases: ['Van Dijk', 'VVD'], metadata: { team: 'Liverpool', position: 'CB', nationality: 'Netherlands' } },
  { name: 'Matthijs de Ligt', type: 'PLAYER', aliases: ['De Ligt'], metadata: { team: 'Manchester United', position: 'CB', nationality: 'Netherlands' } },
  { name: 'Lisandro Martinez', type: 'PLAYER', aliases: ['L. Martinez', 'Licha'], metadata: { team: 'Manchester United', position: 'CB', nationality: 'Argentina' } },
  { name: 'Alexis Mac Allister', type: 'PLAYER', aliases: ['Mac Allister', 'MacAllister'], metadata: { team: 'Liverpool', position: 'CM', nationality: 'Argentina' } },
  { name: 'Sandro Tonali', type: 'PLAYER', aliases: ['Tonali'], metadata: { team: 'Newcastle', position: 'CM', nationality: 'Italy' } },
  { name: 'William Saliba', type: 'PLAYER', aliases: ['Saliba'], metadata: { team: 'Arsenal', position: 'CB', nationality: 'France' } },
  { name: 'Trent Alexander-Arnold', type: 'PLAYER', aliases: ['TAA', 'Trent', 'Alexander-Arnold'], metadata: { team: 'Liverpool', position: 'RB', nationality: 'England' } },
  { name: 'Gabriel Jesus', type: 'PLAYER', aliases: ['G. Jesus', 'Gabriel'], metadata: { team: 'Arsenal', position: 'ST', nationality: 'Brazil' } },
  { name: 'Ollie Watkins', type: 'PLAYER', aliases: ['Watkins'], metadata: { team: 'Aston Villa', position: 'ST', nationality: 'England' } },
  { name: 'James Maddison', type: 'PLAYER', aliases: ['Maddison'], metadata: { team: 'Tottenham', position: 'AM', nationality: 'England' } },
  { name: 'Moises Caicedo', type: 'PLAYER', aliases: ['Caicedo'], metadata: { team: 'Chelsea', position: 'CM', nationality: 'Ecuador' } },
  { name: 'Enzo Fernandez', type: 'PLAYER', aliases: ['Enzo'], metadata: { team: 'Chelsea', position: 'CM', nationality: 'Argentina' } },
  { name: 'Dominik Szoboszlai', type: 'PLAYER', aliases: ['Szoboszlai'], metadata: { team: 'Liverpool', position: 'AM', nationality: 'Hungary' } },
  { name: 'Rodri', type: 'PLAYER', aliases: ['Rodri Hernandez'], metadata: { team: 'Manchester City', position: 'CDM', nationality: 'Spain' } },
  { name: 'Bernardo Silva', type: 'PLAYER', aliases: ['B. Silva', 'Bernardo'], metadata: { team: 'Manchester City', position: 'RW', nationality: 'Portugal' } },
  { name: 'Gabriel Martinelli', type: 'PLAYER', aliases: ['Martinelli'], metadata: { team: 'Arsenal', position: 'LW', nationality: 'Brazil' } },
  { name: 'Kai Havertz', type: 'PLAYER', aliases: ['Havertz'], metadata: { team: 'Arsenal', position: 'ST', nationality: 'Germany' } },
  { name: 'Nicolas Jackson', type: 'PLAYER', aliases: ['N. Jackson', 'Jackson'], metadata: { team: 'Chelsea', position: 'ST', nationality: 'Senegal' } },
  { name: 'Casemiro', type: 'PLAYER', aliases: ['Case'], metadata: { team: 'Manchester United', position: 'CDM', nationality: 'Brazil' } },
  { name: 'Diogo Jota', type: 'PLAYER', aliases: ['Jota', 'D. Jota'], metadata: { team: 'Liverpool', position: 'ST', nationality: 'Portugal' } },
  { name: 'Joao Pedro', type: 'PLAYER', aliases: ['J. Pedro'], metadata: { team: 'Brighton', position: 'ST', nationality: 'Brazil' } },
  { name: 'Eberechi Eze', type: 'PLAYER', aliases: ['Eze'], metadata: { team: 'Crystal Palace', position: 'AM', nationality: 'England' } },
  { name: 'Ivan Toney', type: 'PLAYER', aliases: ['Toney'], metadata: { team: 'Al-Ahli', position: 'ST', nationality: 'England' } },
  { name: 'Jarrod Bowen', type: 'PLAYER', aliases: ['Bowen'], metadata: { team: 'West Ham', position: 'RW', nationality: 'England' } },
  { name: 'Alisson Becker', type: 'PLAYER', aliases: ['Alisson'], metadata: { team: 'Liverpool', position: 'GK', nationality: 'Brazil' } },
  { name: 'Ederson', type: 'PLAYER', aliases: ['Ederson Moraes'], metadata: { team: 'Manchester City', position: 'GK', nationality: 'Brazil' } },
  { name: 'David Raya', type: 'PLAYER', aliases: ['Raya'], metadata: { team: 'Arsenal', position: 'GK', nationality: 'Spain' } },
  { name: 'Ruben Dias', type: 'PLAYER', aliases: ['R. Dias'], metadata: { team: 'Manchester City', position: 'CB', nationality: 'Portugal' } },
  { name: 'Kylian Mbappe', type: 'PLAYER', aliases: ['Mbappe', 'Mbappé'], metadata: { team: 'Real Madrid', position: 'ST', nationality: 'France' } },
  { name: 'Vinicius Junior', type: 'PLAYER', aliases: ['Vinicius Jr', 'Vini Jr', 'Vinicius'], metadata: { team: 'Real Madrid', position: 'LW', nationality: 'Brazil' } },
  { name: 'Jude Bellingham', type: 'PLAYER', aliases: ['Bellingham', 'Jude'], metadata: { team: 'Real Madrid', position: 'AM', nationality: 'England' } },
  { name: 'Lamine Yamal', type: 'PLAYER', aliases: ['Yamal', 'Lamine'], metadata: { team: 'Barcelona', position: 'RW', nationality: 'Spain' } },
  { name: 'Robert Lewandowski', type: 'PLAYER', aliases: ['Lewandowski', 'Lewy'], metadata: { team: 'Barcelona', position: 'ST', nationality: 'Poland' } },
  { name: 'Pedri', type: 'PLAYER', aliases: ['Pedri Gonzalez'], metadata: { team: 'Barcelona', position: 'CM', nationality: 'Spain' } },
  { name: 'Gavi', type: 'PLAYER', aliases: ['Pablo Gavi'], metadata: { team: 'Barcelona', position: 'CM', nationality: 'Spain' } },
  { name: 'Raphinha', type: 'PLAYER', aliases: ['Raphinha Dias'], metadata: { team: 'Barcelona', position: 'LW', nationality: 'Brazil' } },
  { name: 'Antoine Griezmann', type: 'PLAYER', aliases: ['Griezmann', 'Grizi'], metadata: { team: 'Atletico Madrid', position: 'ST', nationality: 'France' } },
  { name: 'Federico Valverde', type: 'PLAYER', aliases: ['Valverde', 'Fede Valverde'], metadata: { team: 'Real Madrid', position: 'CM', nationality: 'Uruguay' } },
  { name: 'Toni Kroos', type: 'PLAYER', aliases: ['Kroos'], metadata: { team: 'Retired', position: 'CM', nationality: 'Germany' } },
  { name: 'Dani Carvajal', type: 'PLAYER', aliases: ['Carvajal'], metadata: { team: 'Real Madrid', position: 'RB', nationality: 'Spain' } },
  { name: 'Eder Militao', type: 'PLAYER', aliases: ['Militao', 'Militão'], metadata: { team: 'Real Madrid', position: 'CB', nationality: 'Brazil' } },
  { name: 'Frenkie de Jong', type: 'PLAYER', aliases: ['De Jong', 'Frenkie'], metadata: { team: 'Barcelona', position: 'CM', nationality: 'Netherlands' } },
  { name: 'Ronald Araujo', type: 'PLAYER', aliases: ['Araujo', 'Araújo'], metadata: { team: 'Barcelona', position: 'CB', nationality: 'Uruguay' } },
  { name: 'Joao Felix', type: 'PLAYER', aliases: ['J. Felix', 'Felix', 'João Félix'], metadata: { team: 'Chelsea', position: 'AM', nationality: 'Portugal' } },
  { name: 'Alexander Sorloth', type: 'PLAYER', aliases: ['Sorloth', 'Sørloth'], metadata: { team: 'Atletico Madrid', position: 'ST', nationality: 'Norway' } },
  { name: 'Arda Guler', type: 'PLAYER', aliases: ['Guler', 'Güler', 'Arda'], metadata: { team: 'Real Madrid', position: 'AM', nationality: 'Turkey' } },
  { name: 'Fermin Lopez', type: 'PLAYER', aliases: ['Fermin', 'Fermín'], metadata: { team: 'Barcelona', position: 'AM', nationality: 'Spain' } },
  { name: 'Pau Cubarsi', type: 'PLAYER', aliases: ['Cubarsi', 'Cubarsí'], metadata: { team: 'Barcelona', position: 'CB', nationality: 'Spain' } },
  { name: 'Lautaro Martinez', type: 'PLAYER', aliases: ['Lautaro', 'L. Martinez'], metadata: { team: 'Inter Milan', position: 'ST', nationality: 'Argentina' } },
  { name: 'Dusan Vlahovic', type: 'PLAYER', aliases: ['Vlahovic', 'Vlahović'], metadata: { team: 'Juventus', position: 'ST', nationality: 'Serbia' } },
  { name: 'Hakan Calhanoglu', type: 'PLAYER', aliases: ['Calhanoglu', 'Çalhanoğlu'], metadata: { team: 'Inter Milan', position: 'CM', nationality: 'Turkey' } },
  { name: 'Rafael Leao', type: 'PLAYER', aliases: ['Leao', 'Leão', 'Rafa Leao'], metadata: { team: 'AC Milan', position: 'LW', nationality: 'Portugal' } },
  { name: 'Victor Osimhen', type: 'PLAYER', aliases: ['Osimhen'], metadata: { team: 'Galatasaray', position: 'ST', nationality: 'Nigeria' } },
  { name: 'Nicolo Barella', type: 'PLAYER', aliases: ['Barella', 'Nicolò'], metadata: { team: 'Inter Milan', position: 'CM', nationality: 'Italy' } },
  { name: 'Pierre Kalulu', type: 'PLAYER', aliases: ['Kalulu'], metadata: { team: 'Juventus', position: 'CB', nationality: 'France', onLoan: true, loanFrom: 'AC Milan' } },
  { name: 'Francesco Pio Esposito', type: 'PLAYER', aliases: ['Pio Esposito', 'F. Esposito'], metadata: { team: 'Spezia', position: 'ST', nationality: 'Italy', onLoan: true, loanFrom: 'Inter Milan' } },
  { name: 'Andrea Cambiaso', type: 'PLAYER', aliases: ['Cambiaso'], metadata: { team: 'Juventus', position: 'LB', nationality: 'Italy' } },
  { name: 'Manuel Locatelli', type: 'PLAYER', aliases: ['Locatelli'], metadata: { team: 'Juventus', position: 'CM', nationality: 'Italy' } },
  { name: 'Piotr Zielinski', type: 'PLAYER', aliases: ['Zielinski', 'Zieliński'], metadata: { team: 'Inter Milan', position: 'CM', nationality: 'Poland' } },
  { name: 'Alessandro Bastoni', type: 'PLAYER', aliases: ['Bastoni'], metadata: { team: 'Inter Milan', position: 'CB', nationality: 'Italy' } },
  { name: 'Khvicha Kvaratskhelia', type: 'PLAYER', aliases: ['Kvaratskhelia', 'Kvara', 'Kvaradona'], metadata: { team: 'PSG', position: 'LW', nationality: 'Georgia' } },
  { name: 'Federico Chiesa', type: 'PLAYER', aliases: ['Chiesa'], metadata: { team: 'Liverpool', position: 'RW', nationality: 'Italy' } },
  { name: 'Paulo Dybala', type: 'PLAYER', aliases: ['Dybala', 'La Joya'], metadata: { team: 'Roma', position: 'AM', nationality: 'Argentina' } },
  { name: 'Ademola Lookman', type: 'PLAYER', aliases: ['Lookman'], metadata: { team: 'Atalanta', position: 'LW', nationality: 'Nigeria' } },
  { name: 'Gianluca Scamacca', type: 'PLAYER', aliases: ['Scamacca'], metadata: { team: 'Atalanta', position: 'ST', nationality: 'Italy' } },
  { name: 'Matteo Darmian', type: 'PLAYER', aliases: ['Darmian'], metadata: { team: 'Inter Milan', position: 'RB', nationality: 'Italy' } },
  { name: 'Federico Dimarco', type: 'PLAYER', aliases: ['Dimarco'], metadata: { team: 'Inter Milan', position: 'LB', nationality: 'Italy' } },
  { name: 'Harry Kane', type: 'PLAYER', aliases: ['Kane'], metadata: { team: 'Bayern Munich', position: 'ST', nationality: 'England' } },
  { name: 'Florian Wirtz', type: 'PLAYER', aliases: ['Wirtz'], metadata: { team: 'Bayer Leverkusen', position: 'AM', nationality: 'Germany' } },
  { name: 'Jamal Musiala', type: 'PLAYER', aliases: ['Musiala'], metadata: { team: 'Bayern Munich', position: 'AM', nationality: 'Germany' } },
  { name: 'Xavi Simons', type: 'PLAYER', aliases: ['X. Simons'], metadata: { team: 'RB Leipzig', position: 'AM', nationality: 'Netherlands', onLoan: true, loanFrom: 'PSG' } },
  { name: 'Serge Gnabry', type: 'PLAYER', aliases: ['Gnabry'], metadata: { team: 'Bayern Munich', position: 'RW', nationality: 'Germany' } },
  { name: 'Leroy Sane', type: 'PLAYER', aliases: ['Sane', 'Sané'], metadata: { team: 'Bayern Munich', position: 'LW', nationality: 'Germany' } },
  { name: 'Joshua Kimmich', type: 'PLAYER', aliases: ['Kimmich'], metadata: { team: 'Bayern Munich', position: 'CM', nationality: 'Germany' } },
  { name: 'Dani Olmo', type: 'PLAYER', aliases: ['D. Olmo', 'Olmo'], metadata: { team: 'Barcelona', position: 'AM', nationality: 'Spain' } },
  { name: 'Granit Xhaka', type: 'PLAYER', aliases: ['Xhaka'], metadata: { team: 'Bayer Leverkusen', position: 'CM', nationality: 'Switzerland' } },
  { name: 'Loic Bade', type: 'PLAYER', aliases: ['Bade', 'Badé'], metadata: { team: 'Sevilla', position: 'CB', nationality: 'France' } },
  { name: 'Ousmane Dembele', type: 'PLAYER', aliases: ['Dembele', 'Dembélé'], metadata: { team: 'PSG', position: 'RW', nationality: 'France' } },
  { name: 'Bradley Barcola', type: 'PLAYER', aliases: ['Barcola'], metadata: { team: 'PSG', position: 'LW', nationality: 'France' } },
  { name: 'Achraf Hakimi', type: 'PLAYER', aliases: ['Hakimi'], metadata: { team: 'PSG', position: 'RB', nationality: 'Morocco' } },
  { name: 'Goncalo Ramos', type: 'PLAYER', aliases: ['G. Ramos', 'Gonçalo Ramos'], metadata: { team: 'PSG', position: 'ST', nationality: 'Portugal' } },
  { name: 'Randal Kolo Muani', type: 'PLAYER', aliases: ['Kolo Muani', 'RKM'], metadata: { team: 'Juventus', position: 'ST', nationality: 'France', onLoan: true, loanFrom: 'PSG' } },
  { name: 'Jonathan David', type: 'PLAYER', aliases: ['J. David'], metadata: { team: 'Lille', position: 'ST', nationality: 'Canada' } },
  { name: 'Mason Greenwood', type: 'PLAYER', aliases: ['Greenwood'], metadata: { team: 'Marseille', position: 'RW', nationality: 'England' } },
  { name: 'Pierre-Emerick Aubameyang', type: 'PLAYER', aliases: ['Aubameyang', 'Auba', 'PEA'], metadata: { team: 'Marseille', position: 'ST', nationality: 'Gabon' } },
  { name: 'Cristiano Ronaldo', type: 'PLAYER', aliases: ['Ronaldo', 'CR7', 'Cristiano'], metadata: { team: 'Al Nassr', position: 'ST', nationality: 'Portugal' } },
  { name: 'Lionel Messi', type: 'PLAYER', aliases: ['Messi', 'Leo Messi', 'Leo'], metadata: { team: 'Inter Miami', position: 'RW', nationality: 'Argentina' } },
  { name: 'Neymar Jr', type: 'PLAYER', aliases: ['Neymar', 'Ney'], metadata: { team: 'Santos', position: 'LW', nationality: 'Brazil' } },
  { name: 'Karim Benzema', type: 'PLAYER', aliases: ['Benzema', 'Benz'], metadata: { team: 'Al-Ittihad', position: 'ST', nationality: 'France' } },
  { name: 'Sadio Mane', type: 'PLAYER', aliases: ['Mane', 'Mané'], metadata: { team: 'Al-Nassr', position: 'LW', nationality: 'Senegal' } },
  { name: 'Rodrygo', type: 'PLAYER', aliases: ['Rodrygo Goes'], metadata: { team: 'Real Madrid', position: 'RW', nationality: 'Brazil' } },
  { name: 'Viktor Gyokeres', type: 'PLAYER', aliases: ['Gyokeres', 'Gyökeres'], metadata: { team: 'Sporting CP', position: 'ST', nationality: 'Sweden' } },
  { name: 'Nico Williams', type: 'PLAYER', aliases: ['N. Williams'], metadata: { team: 'Athletic Bilbao', position: 'LW', nationality: 'Spain' } },
  { name: 'Joao Neves', type: 'PLAYER', aliases: ['João Neves'], metadata: { team: 'PSG', position: 'CM', nationality: 'Portugal' } },
  { name: 'Harry Maguire', type: 'PLAYER', aliases: ['Maguire'], metadata: { team: 'Manchester United', position: 'CB', nationality: 'England' } },
  { name: 'Gianluca Di Marzio', type: 'JOURNALIST', aliases: ['Di Marzio'], metadata: { specialty: 'transfers', outlet: 'Sky Italia' } },
  { name: 'Arne Slot', type: 'MANAGER', aliases: ['Slot'], metadata: { team: 'Liverpool', nationality: 'Netherlands' } },
  { name: 'Mauricio Pochettino', type: 'MANAGER', aliases: ['Pochettino', 'Poch'], metadata: { team: 'USMNT', nationality: 'Argentina' } },
  { name: 'Erik ten Hag', type: 'MANAGER', aliases: ['Ten Hag', 'ETH'], metadata: { team: 'Free Agent', nationality: 'Netherlands' } },
]

const CLUBS: EntityDef[] = [
  { name: 'Manchester United', type: 'CLUB', aliases: ['Man United', 'Man Utd', 'MUFC', 'Red Devils'], metadata: { league: 'Premier League', country: 'England', stadium: 'Old Trafford' } },
  { name: 'Manchester City', type: 'CLUB', aliases: ['Man City', 'MCFC', 'Citizens', 'City'], metadata: { league: 'Premier League', country: 'England', stadium: 'Etihad Stadium' } },
  { name: 'Liverpool', type: 'CLUB', aliases: ['LFC', 'Reds', 'The Reds'], metadata: { league: 'Premier League', country: 'England', stadium: 'Anfield' } },
  { name: 'Arsenal', type: 'CLUB', aliases: ['AFC', 'Gunners', 'The Gunners'], metadata: { league: 'Premier League', country: 'England', stadium: 'Emirates Stadium' } },
  { name: 'Chelsea', type: 'CLUB', aliases: ['CFC', 'Blues', 'The Blues'], metadata: { league: 'Premier League', country: 'England', stadium: 'Stamford Bridge' } },
  { name: 'Tottenham Hotspur', type: 'CLUB', aliases: ['Tottenham', 'Spurs', 'THFC'], metadata: { league: 'Premier League', country: 'England', stadium: 'Tottenham Hotspur Stadium' } },
  { name: 'Newcastle United', type: 'CLUB', aliases: ['Newcastle', 'NUFC', 'Magpies', 'Toon'], metadata: { league: 'Premier League', country: 'England', stadium: 'St James Park' } },
  { name: 'Aston Villa', type: 'CLUB', aliases: ['Villa', 'AVFC', 'Villans'], metadata: { league: 'Premier League', country: 'England', stadium: 'Villa Park' } },
  { name: 'West Ham United', type: 'CLUB', aliases: ['West Ham', 'WHU', 'Hammers', 'Irons'], metadata: { league: 'Premier League', country: 'England', stadium: 'London Stadium' } },
  { name: 'Brighton & Hove Albion', type: 'CLUB', aliases: ['Brighton', 'BHAFC', 'Seagulls'], metadata: { league: 'Premier League', country: 'England', stadium: 'Amex Stadium' } },
  { name: 'Crystal Palace', type: 'CLUB', aliases: ['Palace', 'CPFC', 'Eagles'], metadata: { league: 'Premier League', country: 'England', stadium: 'Selhurst Park' } },
  { name: 'Everton', type: 'CLUB', aliases: ['EFC', 'Toffees', 'The Toffees'], metadata: { league: 'Premier League', country: 'England', stadium: 'Goodison Park' } },
  { name: 'Fulham', type: 'CLUB', aliases: ['FFC', 'Cottagers'], metadata: { league: 'Premier League', country: 'England', stadium: 'Craven Cottage' } },
  { name: 'Wolverhampton Wanderers', type: 'CLUB', aliases: ['Wolves', 'Wolverhampton', 'WWFC'], metadata: { league: 'Premier League', country: 'England', stadium: 'Molineux' } },
  { name: 'Bournemouth', type: 'CLUB', aliases: ['AFC Bournemouth', 'AFCB', 'Cherries'], metadata: { league: 'Premier League', country: 'England', stadium: 'Vitality Stadium' } },
  { name: 'Nottingham Forest', type: 'CLUB', aliases: ['Forest', 'NFFC', 'Nottm Forest'], metadata: { league: 'Premier League', country: 'England', stadium: 'City Ground' } },
  { name: 'Brentford', type: 'CLUB', aliases: ['Bees', 'BFC'], metadata: { league: 'Premier League', country: 'England', stadium: 'Gtech Community Stadium' } },
  { name: 'Ipswich Town', type: 'CLUB', aliases: ['Ipswich', 'ITFC', 'Tractor Boys'], metadata: { league: 'Premier League', country: 'England', stadium: 'Portman Road' } },
  { name: 'Leicester City', type: 'CLUB', aliases: ['Leicester', 'LCFC', 'Foxes'], metadata: { league: 'Premier League', country: 'England', stadium: 'King Power Stadium' } },
  { name: 'Southampton', type: 'CLUB', aliases: ['Saints', 'SFC'], metadata: { league: 'Premier League', country: 'England', stadium: 'St Marys Stadium' } },
  { name: 'Real Madrid', type: 'CLUB', aliases: ['Madrid', 'Real', 'Los Blancos', 'RMCF'], metadata: { league: 'La Liga', country: 'Spain', stadium: 'Santiago Bernabeu' } },
  { name: 'Barcelona', type: 'CLUB', aliases: ['Barca', 'Barça', 'FCB', 'Blaugrana'], metadata: { league: 'La Liga', country: 'Spain', stadium: 'Camp Nou' } },
  { name: 'Atletico Madrid', type: 'CLUB', aliases: ['Atletico', 'Atleti', 'Atlético', 'Colchoneros'], metadata: { league: 'La Liga', country: 'Spain', stadium: 'Metropolitano' } },
  { name: 'Real Sociedad', type: 'CLUB', aliases: ['Sociedad', 'La Real', 'RSFC'], metadata: { league: 'La Liga', country: 'Spain' } },
  { name: 'Real Betis', type: 'CLUB', aliases: ['Betis', 'Verdiblancos'], metadata: { league: 'La Liga', country: 'Spain' } },
  { name: 'Sevilla', type: 'CLUB', aliases: ['SFC', 'Sevillistas'], metadata: { league: 'La Liga', country: 'Spain' } },
  { name: 'Athletic Bilbao', type: 'CLUB', aliases: ['Athletic', 'Bilbao', 'Los Leones'], metadata: { league: 'La Liga', country: 'Spain' } },
  { name: 'Villarreal', type: 'CLUB', aliases: ['Yellow Submarine', 'Submarino Amarillo'], metadata: { league: 'La Liga', country: 'Spain' } },
  { name: 'Valencia', type: 'CLUB', aliases: ['VCF', 'Los Che'], metadata: { league: 'La Liga', country: 'Spain' } },
  { name: 'Girona', type: 'CLUB', aliases: ['Girona FC'], metadata: { league: 'La Liga', country: 'Spain' } },
  { name: 'Inter Milan', type: 'CLUB', aliases: ['Inter', 'Internazionale', 'Nerazzurri'], metadata: { league: 'Serie A', country: 'Italy', stadium: 'San Siro' } },
  { name: 'AC Milan', type: 'CLUB', aliases: ['Milan', 'Rossoneri'], metadata: { league: 'Serie A', country: 'Italy', stadium: 'San Siro' } },
  { name: 'Juventus', type: 'CLUB', aliases: ['Juve', 'Old Lady', 'Bianconeri'], metadata: { league: 'Serie A', country: 'Italy', stadium: 'Allianz Stadium' } },
  { name: 'Napoli', type: 'CLUB', aliases: ['SSC Napoli', 'Partenopei', 'Gli Azzurri'], metadata: { league: 'Serie A', country: 'Italy', stadium: 'Stadio Maradona' } },
  { name: 'Roma', type: 'CLUB', aliases: ['AS Roma', 'Giallorossi', 'Lupi'], metadata: { league: 'Serie A', country: 'Italy', stadium: 'Stadio Olimpico' } },
  { name: 'Lazio', type: 'CLUB', aliases: ['SS Lazio', 'Biancocelesti', 'Aquile'], metadata: { league: 'Serie A', country: 'Italy', stadium: 'Stadio Olimpico' } },
  { name: 'Atalanta', type: 'CLUB', aliases: ['La Dea', 'Atalanta BC'], metadata: { league: 'Serie A', country: 'Italy' } },
  { name: 'Fiorentina', type: 'CLUB', aliases: ['Viola', 'ACF Fiorentina'], metadata: { league: 'Serie A', country: 'Italy' } },
  { name: 'Bologna', type: 'CLUB', aliases: ['BFC', 'Rossoblu'], metadata: { league: 'Serie A', country: 'Italy' } },
  { name: 'Torino', type: 'CLUB', aliases: ['Toro', 'Torino FC'], metadata: { league: 'Serie A', country: 'Italy' } },
  { name: 'Bayern Munich', type: 'CLUB', aliases: ['Bayern', 'FCB', 'FC Bayern', 'Bavarians'], metadata: { league: 'Bundesliga', country: 'Germany', stadium: 'Allianz Arena' } },
  { name: 'Borussia Dortmund', type: 'CLUB', aliases: ['Dortmund', 'BVB', 'Die Borussen'], metadata: { league: 'Bundesliga', country: 'Germany', stadium: 'Signal Iduna Park' } },
  { name: 'RB Leipzig', type: 'CLUB', aliases: ['Leipzig', 'RBL', 'Die Roten Bullen'], metadata: { league: 'Bundesliga', country: 'Germany' } },
  { name: 'Bayer Leverkusen', type: 'CLUB', aliases: ['Leverkusen', 'Werkself', 'B04'], metadata: { league: 'Bundesliga', country: 'Germany' } },
  { name: 'Eintracht Frankfurt', type: 'CLUB', aliases: ['Frankfurt', 'SGE', 'Eintracht'], metadata: { league: 'Bundesliga', country: 'Germany' } },
  { name: 'VfB Stuttgart', type: 'CLUB', aliases: ['Stuttgart', 'VfB'], metadata: { league: 'Bundesliga', country: 'Germany' } },
  { name: 'Borussia Monchengladbach', type: 'CLUB', aliases: ['Gladbach', 'BMG', 'Monchengladbach', 'Mönchengladbach'], metadata: { league: 'Bundesliga', country: 'Germany' } },
  { name: 'VfL Wolfsburg', type: 'CLUB', aliases: ['Wolfsburg'], metadata: { league: 'Bundesliga', country: 'Germany' } },
  { name: 'Paris Saint-Germain', type: 'CLUB', aliases: ['PSG', 'Paris', 'Les Parisiens'], metadata: { league: 'Ligue 1', country: 'France', stadium: 'Parc des Princes' } },
  { name: 'Olympique Marseille', type: 'CLUB', aliases: ['Marseille', 'OM', 'Les Olympiens'], metadata: { league: 'Ligue 1', country: 'France' } },
  { name: 'Olympique Lyon', type: 'CLUB', aliases: ['Lyon', 'OL', 'Les Gones'], metadata: { league: 'Ligue 1', country: 'France' } },
  { name: 'AS Monaco', type: 'CLUB', aliases: ['Monaco', 'ASM'], metadata: { league: 'Ligue 1', country: 'France' } },
  { name: 'LOSC Lille', type: 'CLUB', aliases: ['Lille', 'LOSC', 'Les Dogues'], metadata: { league: 'Ligue 1', country: 'France' } },
  { name: 'OGC Nice', type: 'CLUB', aliases: ['Nice', 'Les Aiglons'], metadata: { league: 'Ligue 1', country: 'France' } },
  { name: 'Benfica', type: 'CLUB', aliases: ['SL Benfica', 'Encarnados', 'Aguias'], metadata: { league: 'Liga Portugal', country: 'Portugal' } },
  { name: 'Porto', type: 'CLUB', aliases: ['FC Porto', 'Dragoes'], metadata: { league: 'Liga Portugal', country: 'Portugal' } },
  { name: 'Sporting CP', type: 'CLUB', aliases: ['Sporting', 'Sporting Lisbon', 'Leoes'], metadata: { league: 'Liga Portugal', country: 'Portugal' } },
  { name: 'Ajax', type: 'CLUB', aliases: ['AFC Ajax', 'Godenzonen'], metadata: { league: 'Eredivisie', country: 'Netherlands' } },
  { name: 'PSV Eindhoven', type: 'CLUB', aliases: ['PSV', 'Boeren'], metadata: { league: 'Eredivisie', country: 'Netherlands' } },
  { name: 'Feyenoord', type: 'CLUB', aliases: ['Feyenoord Rotterdam'], metadata: { league: 'Eredivisie', country: 'Netherlands' } },
  { name: 'Celtic', type: 'CLUB', aliases: ['Celtic FC', 'Bhoys', 'Hoops'], metadata: { league: 'Scottish Premiership', country: 'Scotland' } },
  { name: 'Rangers', type: 'CLUB', aliases: ['Rangers FC', 'Gers'], metadata: { league: 'Scottish Premiership', country: 'Scotland' } },
  { name: 'Galatasaray', type: 'CLUB', aliases: ['Gala', 'Cimbom'], metadata: { league: 'Super Lig', country: 'Turkey' } },
  { name: 'Fenerbahce', type: 'CLUB', aliases: ['Fener', 'Fenerbahçe'], metadata: { league: 'Super Lig', country: 'Turkey' } },
]

const COMPETITIONS: EntityDef[] = [
  { name: 'Premier League', type: 'LEAGUE', aliases: ['EPL', 'English Premier League', 'PL'] },
  { name: 'La Liga', type: 'LEAGUE', aliases: ['LaLiga', 'Spanish La Liga', 'Primera Division'] },
  { name: 'Serie A', type: 'LEAGUE', aliases: ['Italian Serie A', 'Calcio'] },
  { name: 'Bundesliga', type: 'LEAGUE', aliases: ['German Bundesliga', 'BuLi'] },
  { name: 'Ligue 1', type: 'LEAGUE', aliases: ['French Ligue 1', 'L1'] },
  { name: 'Eredivisie', type: 'LEAGUE', aliases: ['Dutch Eredivisie'] },
  { name: 'Liga Portugal', type: 'LEAGUE', aliases: ['Primeira Liga', 'Portuguese League'] },
  { name: 'Scottish Premiership', type: 'LEAGUE', aliases: ['SPFL', 'Scottish Premier League'] },
  { name: 'Super Lig', type: 'LEAGUE', aliases: ['Turkish Super Lig', 'Süper Lig'] },
  { name: 'Saudi Pro League', type: 'LEAGUE', aliases: ['SPL', 'Roshn Saudi League'] },
  { name: 'MLS', type: 'LEAGUE', aliases: ['Major League Soccer'] },
  { name: 'Championship', type: 'LEAGUE', aliases: ['EFL Championship', 'English Championship'] },
  { name: 'Champions League', type: 'COMPETITION', aliases: ['UCL', 'CL', 'UEFA Champions League'] },
  { name: 'Europa League', type: 'COMPETITION', aliases: ['UEL', 'EL', 'UEFA Europa League'] },
  { name: 'Conference League', type: 'COMPETITION', aliases: ['UECL', 'UEFA Conference League'] },
  { name: 'Club World Cup', type: 'COMPETITION', aliases: ['FIFA Club World Cup', 'CWC'] },
  { name: 'FA Cup', type: 'COMPETITION', aliases: ['Emirates FA Cup'] },
  { name: 'Carabao Cup', type: 'COMPETITION', aliases: ['League Cup', 'EFL Cup'] },
  { name: 'Copa del Rey', type: 'COMPETITION', aliases: ['Spanish Cup'] },
  { name: 'Coppa Italia', type: 'COMPETITION', aliases: ['Italian Cup'] },
  { name: 'DFB-Pokal', type: 'COMPETITION', aliases: ['German Cup', 'DFB Pokal'] },
  { name: 'Coupe de France', type: 'COMPETITION', aliases: ['French Cup'] },
  { name: 'World Cup', type: 'COMPETITION', aliases: ['FIFA World Cup', 'WC'] },
  { name: 'European Championship', type: 'COMPETITION', aliases: ['Euro', 'Euros', 'UEFA Euro'] },
  { name: 'Copa America', type: 'COMPETITION', aliases: ['Copa América'] },
  { name: 'Africa Cup of Nations', type: 'COMPETITION', aliases: ['AFCON', 'CAN'] },
  { name: 'Nations League', type: 'COMPETITION', aliases: ['UEFA Nations League', 'UNL'] },
  { name: 'Community Shield', type: 'COMPETITION', aliases: ['FA Community Shield'] },
  { name: 'Super Cup', type: 'COMPETITION', aliases: ['UEFA Super Cup'] },
  { name: 'Supercopa de Espana', type: 'COMPETITION', aliases: ['Spanish Super Cup'] },
  { name: 'El Clasico', type: 'COMPETITION', aliases: ['Clasico', 'El Clásico'] },
  { name: 'Derby della Madonnina', type: 'COMPETITION', aliases: ['Milan Derby'] },
  { name: 'Derby dItalia', type: 'COMPETITION', aliases: ['Inter vs Juventus', 'Juventus vs Inter'] },
  { name: 'North London Derby', type: 'COMPETITION', aliases: ['Arsenal vs Tottenham', 'Tottenham vs Arsenal'] },
  { name: 'Manchester Derby', type: 'COMPETITION', aliases: ['Man City vs Man United', 'Man United vs Man City'] },
  { name: 'Merseyside Derby', type: 'COMPETITION', aliases: ['Liverpool vs Everton', 'Everton vs Liverpool'] },
  { name: 'Northwest Derby', type: 'COMPETITION', aliases: ['Liverpool vs Man United', 'Man United vs Liverpool'] },
  { name: 'Der Klassiker', type: 'COMPETITION', aliases: ['Bayern vs Dortmund', 'Dortmund vs Bayern'] },
]

const MANAGERS: EntityDef[] = [
  { name: 'Pep Guardiola', type: 'MANAGER', aliases: ['Guardiola', 'Pep'], metadata: { team: 'Manchester City', nationality: 'Spain' } },
  { name: 'Jurgen Klopp', type: 'MANAGER', aliases: ['Klopp', 'Jürgen Klopp'], metadata: { team: 'Unemployed', nationality: 'Germany' } },
  { name: 'Carlo Ancelotti', type: 'MANAGER', aliases: ['Ancelotti', 'Don Carlo'], metadata: { team: 'Real Madrid', nationality: 'Italy' } },
  { name: 'Mikel Arteta', type: 'MANAGER', aliases: ['Arteta'], metadata: { team: 'Arsenal', nationality: 'Spain' } },
  { name: 'Ruben Amorim', type: 'MANAGER', aliases: ['Amorim', 'Rúben Amorim'], metadata: { team: 'Manchester United', nationality: 'Portugal' } },
  { name: 'Enzo Maresca', type: 'MANAGER', aliases: ['Maresca'], metadata: { team: 'Chelsea', nationality: 'Italy' } },
  { name: 'Hansi Flick', type: 'MANAGER', aliases: ['Flick'], metadata: { team: 'Barcelona', nationality: 'Germany' } },
  { name: 'Simone Inzaghi', type: 'MANAGER', aliases: ['S. Inzaghi', 'Inzaghi'], metadata: { team: 'Inter Milan', nationality: 'Italy' } },
  { name: 'Thiago Motta', type: 'MANAGER', aliases: ['T. Motta'], metadata: { team: 'Juventus', nationality: 'Italy' } },
  { name: 'Xabi Alonso', type: 'MANAGER', aliases: ['Xabi'], metadata: { team: 'Bayer Leverkusen', nationality: 'Spain' } },
  { name: 'Luis Enrique', type: 'MANAGER', aliases: ['Lucho'], metadata: { team: 'PSG', nationality: 'Spain' } },
  { name: 'Diego Simeone', type: 'MANAGER', aliases: ['Simeone', 'Cholo', 'El Cholo'], metadata: { team: 'Atletico Madrid', nationality: 'Argentina' } },
  { name: 'Unai Emery', type: 'MANAGER', aliases: ['Emery'], metadata: { team: 'Aston Villa', nationality: 'Spain' } },
  { name: 'Ange Postecoglou', type: 'MANAGER', aliases: ['Postecoglou', 'Ange'], metadata: { team: 'Tottenham', nationality: 'Australia' } },
  { name: 'Eddie Howe', type: 'MANAGER', aliases: ['Howe'], metadata: { team: 'Newcastle', nationality: 'England' } },
  { name: 'Marco Silva', type: 'MANAGER', aliases: ['M. Silva'], metadata: { team: 'Fulham', nationality: 'Portugal' } },
  { name: 'Nuno Espirito Santo', type: 'MANAGER', aliases: ['Nuno'], metadata: { team: 'Nottingham Forest', nationality: 'Portugal' } },
  { name: 'Thomas Frank', type: 'MANAGER', aliases: ['Frank'], metadata: { team: 'Brentford', nationality: 'Denmark' } },
  { name: 'Antonio Conte', type: 'MANAGER', aliases: ['Conte'], metadata: { team: 'Napoli', nationality: 'Italy' } },
  { name: 'Gian Piero Gasperini', type: 'MANAGER', aliases: ['Gasperini'], metadata: { team: 'Atalanta', nationality: 'Italy' } },
  { name: 'Jose Mourinho', type: 'MANAGER', aliases: ['Mourinho', 'Mou', 'The Special One'], metadata: { team: 'Fenerbahce', nationality: 'Portugal' } },
  { name: 'Zinedine Zidane', type: 'MANAGER', aliases: ['Zidane', 'Zizou'], metadata: { team: 'Unemployed', nationality: 'France' } },
  { name: 'Michael Carrick', type: 'MANAGER', aliases: ['Carrick'], metadata: { team: 'Middlesbrough', nationality: 'England' } },
  { name: 'Sean Dyche', type: 'MANAGER', aliases: ['Dyche'], metadata: { team: 'Everton', nationality: 'England' } },
  { name: "Gary O'Neill", type: 'MANAGER', aliases: ["O'Neill"], metadata: { team: 'Wolverhampton', nationality: 'England' } },
  { name: 'Roberto De Zerbi', type: 'MANAGER', aliases: ['De Zerbi'], metadata: { team: 'Marseille', nationality: 'Italy' } },
  { name: 'Vincent Kompany', type: 'MANAGER', aliases: ['Kompany'], metadata: { team: 'Bayern Munich', nationality: 'Belgium' } },
  { name: 'Nuri Sahin', type: 'MANAGER', aliases: ['Sahin', 'Şahin'], metadata: { team: 'Borussia Dortmund', nationality: 'Turkey' } },
]

const VENUES: EntityDef[] = [
  { name: 'Old Trafford', type: 'VENUE', aliases: ['Theatre of Dreams'], metadata: { club: 'Manchester United' } },
  { name: 'Anfield', type: 'VENUE', aliases: ['Anfield Road'], metadata: { club: 'Liverpool' } },
  { name: 'Emirates Stadium', type: 'VENUE', aliases: ['The Emirates'], metadata: { club: 'Arsenal' } },
  { name: 'Etihad Stadium', type: 'VENUE', aliases: ['The Etihad'], metadata: { club: 'Manchester City' } },
  { name: 'Stamford Bridge', type: 'VENUE', aliases: ['The Bridge'], metadata: { club: 'Chelsea' } },
  { name: 'Santiago Bernabeu', type: 'VENUE', aliases: ['Bernabeu', 'Bernabéu'], metadata: { club: 'Real Madrid' } },
  { name: 'Camp Nou', type: 'VENUE', aliases: ['Spotify Camp Nou', 'Nou Camp'], metadata: { club: 'Barcelona' } },
  { name: 'San Siro', type: 'VENUE', aliases: ['Giuseppe Meazza', 'Meazza'], metadata: { club: 'Inter Milan' } },
  { name: 'Allianz Arena', type: 'VENUE', aliases: [], metadata: { club: 'Bayern Munich' } },
  { name: 'Parc des Princes', type: 'VENUE', aliases: ['Le Parc'], metadata: { club: 'PSG' } },
  { name: 'Signal Iduna Park', type: 'VENUE', aliases: ['Westfalenstadion', 'Yellow Wall'], metadata: { club: 'Borussia Dortmund' } },
  { name: 'Allianz Stadium', type: 'VENUE', aliases: ['J Stadium'], metadata: { club: 'Juventus' } },
  { name: 'Stadio Olimpico', type: 'VENUE', aliases: ['Olimpico'], metadata: { club: 'Roma' } },
  { name: 'Wembley Stadium', type: 'VENUE', aliases: ['Wembley'], metadata: { club: 'England National Team' } },
]

const NOTABLE: EntityDef[] = [
  { name: 'Federico La Penna', type: 'REFEREE', aliases: ['La Penna'], metadata: { country: 'Italy' } },
  { name: 'Anthony Taylor', type: 'REFEREE', aliases: ['A. Taylor'], metadata: { country: 'England' } },
  { name: 'Michael Oliver', type: 'REFEREE', aliases: ['M. Oliver'], metadata: { country: 'England' } },
  { name: 'Jorge Mendes', type: 'AGENT', aliases: ['Mendes', 'Gestifute'] },
  { name: 'Mino Raiola', type: 'AGENT', aliases: ['Raiola'], metadata: { note: 'Deceased 2022, agency continues' } },
  { name: 'FIFA', type: 'ORGANIZATION', aliases: ['Federation Internationale de Football Association'] },
  { name: 'UEFA', type: 'ORGANIZATION', aliases: ['Union of European Football Associations'] },
  { name: 'Financial Fair Play', type: 'CONCEPT', aliases: ['FFP', 'Financial Sustainability Rules', 'PSR'] },
  { name: 'VAR', type: 'CONCEPT', aliases: ['Video Assistant Referee', 'Video Review'] },
  { name: 'Transfer Window', type: 'CONCEPT', aliases: ['January Window', 'Summer Window', 'Deadline Day'] },
  { name: 'Fabrizio Romano', type: 'JOURNALIST', aliases: ['Romano', 'Fab Romano', 'Here We Go'] },
  { name: 'David Ornstein', type: 'JOURNALIST', aliases: ['Ornstein', 'Orny'] },
]

export async function POST() {
  const ALL_ENTITIES = [...PLAYERS, ...CLUBS, ...COMPETITIONS, ...MANAGERS, ...VENUES, ...NOTABLE]

  let created = 0

  for (const entity of ALL_ENTITIES) {
    try {
      await prisma.entity.upsert({
        where: { name: entity.name },
        update: {
          type: entity.type,
          aliases: entity.aliases || [],
          metadata: (entity.metadata || {}) as Prisma.InputJsonValue,
        },
        create: {
          name: entity.name,
          type: entity.type,
          aliases: entity.aliases || [],
          metadata: (entity.metadata || {}) as Prisma.InputJsonValue,
        },
      })
      created++
    } catch (e) {
      console.error(`Failed: ${entity.name}`, e)
    }
  }

  return NextResponse.json({
    created,
    total: ALL_ENTITIES.length,
    breakdown: {
      players: PLAYERS.length,
      clubs: CLUBS.length,
      competitions: COMPETITIONS.length,
      managers: MANAGERS.length,
      venues: VENUES.length,
      notable: NOTABLE.length,
    },
  })
}
