/**
 * Language Configuration for AI Engine — BCMS + International
 *
 * Provides language-specific vocabulary, grammar rules, and forbidden terms
 * for generating sports journalism in the correct national standard variant.
 *
 * BCMS = Bosnian, Croatian, Montenegrin, Serbian — four national standard
 * varieties of one pluricentric language with real lexical, phonological,
 * and morphological differences that MUST be respected.
 */

export type LanguageCode = 'bs' | 'hr' | 'sr' | 'sr-Latn' | 'sr-Cyrl' | 'cnr' | 'en' | 'ar' | 'tr' | 'de' | 'fr';

export interface LanguageConfig {
  code: LanguageCode;
  name: string;
  nativeName: string;
  script: 'latin' | 'cyrillic' | 'arabic';
  dialect: 'ijekavica' | 'ekavica' | 'none';
  sportTerms: Record<string, string>;
  lexicon: Record<string, string>;
  grammarRules: string[];
  forbiddenTerms: string[];
}

export const LANGUAGE_CONFIGS: Record<string, LanguageConfig> = {
  bs: {
    code: 'bs',
    name: 'Bosnian',
    nativeName: 'Bosanski',
    script: 'latin',
    dialect: 'ijekavica',
    sportTerms: {
      football: 'fudbal',
      team: 'tim',
      match: 'utakmica',
      goal: 'gol',
      goalkeeper: 'golman',
      referee: 'sudija',
      penalty: 'penal',
      offside: 'ofsajd',
      corner: 'korner',
      halftime: 'poluvrijeme',
      victory: 'pobjeda',
      defeat: 'poraz',
      draw: 'nerješeno',
      shot: 'udarac',
      shots_on_target: 'udarci u okvir',
      possession: 'posjed lopte',
      foul: 'prekršaj',
      yellow_card: 'žuti karton',
      red_card: 'crveni karton',
      substitution: 'izmjena',
      assist: 'asistencija',
      standings: 'tabela',
      matchday: 'kolo',
    },
    lexicon: {
      history: 'historija',
      thousand: 'hiljada',
      week: 'sedmica',
      coffee: 'kahva',
      air: 'zrak',
      what_interrogative: 'šta',
    },
    grammarRules: [
      'Koristi IJEKAVICU: mlijeko, lijep, dijete, svijet, rijeka',
      'Koristi LATINICU',
      'Svi dijakritici obavezni: š, đ, č, ć, ž',
      'Čuvaj glas H: lahko, kahva, mehko (ne: lako, kafa, meko)',
      'Turski/arapski pozajmljenice su dozvoljene i kulturno značajne: čaršija, mahala, komšija, sokak',
      'Upitna zamjenica: šta (ne: što)',
      'Koristiti i infinitiv i da+prezent formu',
    ],
    forbiddenTerms: [
      'nogomet',
      'pogodak',
      'vratar',
      'sudac',
      'momčad',
      'tisuća',
      'povijest',
      'glazba',
      'zaleđe',
      'pobeda',
      'nedelja',
      'mleko',
      'lep',
    ],
  },
  hr: {
    code: 'hr',
    name: 'Croatian',
    nativeName: 'Hrvatski',
    script: 'latin',
    dialect: 'ijekavica',
    sportTerms: {
      football: 'nogomet',
      team: 'momčad',
      match: 'utakmica',
      goal: 'pogodak',
      goalkeeper: 'vratar',
      referee: 'sudac',
      penalty: 'jedanaesterac',
      offside: 'zaleđe',
      corner: 'udarac iz kuta',
      halftime: 'poluvrijeme',
      victory: 'pobjeda',
      defeat: 'poraz',
      draw: 'neodlučeno',
      shot: 'udarac',
      shots_on_target: 'udarci u okvir',
      possession: 'posjed lopte',
      foul: 'prekršaj',
      yellow_card: 'žuti karton',
      red_card: 'crveni karton',
      substitution: 'izmjena',
      assist: 'asistencija',
      standings: 'ljestvica',
      matchday: 'kolo',
    },
    lexicon: {
      history: 'povijest',
      thousand: 'tisuća',
      week: 'tjedan',
      coffee: 'kava',
      air: 'zrak',
      what_interrogative: 'što',
    },
    grammarRules: [
      'Koristi IJEKAVICU: mlijeko, lijep, dijete, svijet, rijeka',
      'Koristi LATINICU',
      'Svi dijakritici obavezni: š, đ, č, ć, ž',
      'Upitna zamjenica: što (ne: šta)',
      'Preferirati infinitiv: želim ići (ne: želim da idem)',
      'Hrvatski purizam: koristiti domaće riječi umjesto internacionalizama gdje postoje',
      'Budućnost: imat ću (odvojeno), ne imaću',
    ],
    forbiddenTerms: [
      'fudbal',
      'golman',
      'sudija',
      'ofsajd',
      'korner',
      'hiljada',
      'historija',
      'muzika',
      'kahva',
    ],
  },
  sr: {
    code: 'sr',
    name: 'Serbian (Cyrillic)',
    nativeName: 'Српски',
    script: 'cyrillic',
    dialect: 'ekavica',
    sportTerms: {
      football: 'fudbal',
      team: 'tim',
      match: 'utakmica',
      goal: 'gol',
      goalkeeper: 'golman',
      referee: 'sudija',
      penalty: 'penal',
      offside: 'ofsajd',
      corner: 'korner',
      halftime: 'poluvreme',
      victory: 'pobeda',
      defeat: 'poraz',
      draw: 'nerešeno',
      shot: 'udarac',
      shots_on_target: 'udarci u okvir',
      possession: 'posed lopte',
      foul: 'prekršaj',
      yellow_card: 'žuti karton',
      red_card: 'crveni karton',
      substitution: 'izmena',
      assist: 'asistencija',
      standings: 'tabela',
      matchday: 'kolo',
    },
    lexicon: {
      history: 'istorija',
      thousand: 'hiljada',
      week: 'nedelja',
      coffee: 'kafa',
      air: 'vazduh',
      what_interrogative: 'šta',
    },
    grammarRules: [
      'Koristi EKAVICU: mleko, lep, dete, svet, reka',
      'Koristi ĆIRILICU za output',
      'Preferirati da+prezent: želim da idem (ne: želim ići)',
      'Budućnost: imaću (spojeno)',
      'Upitna zamjenica: šta',
    ],
    forbiddenTerms: [
      'nogomet', 'vratar', 'sudac', 'momčad', 'tisuća',
      'povijest', 'glazba', 'zaleđe', 'tjedan',
    ],
  },
  'sr-Latn': {
    code: 'sr-Latn',
    name: 'Serbian (Latin)',
    nativeName: 'Srpski',
    script: 'latin',
    dialect: 'ekavica',
    sportTerms: {
      football: 'fudbal',
      team: 'tim',
      match: 'utakmica',
      goal: 'gol',
      goalkeeper: 'golman',
      referee: 'sudija',
      penalty: 'penal',
      offside: 'ofsajd',
      corner: 'korner',
      halftime: 'poluvreme',
      victory: 'pobeda',
      defeat: 'poraz',
      draw: 'nerešeno',
      shot: 'udarac',
      shots_on_target: 'udarci u okvir',
      possession: 'posed lopte',
      foul: 'prekršaj',
      yellow_card: 'žuti karton',
      red_card: 'crveni karton',
      substitution: 'izmena',
      assist: 'asistencija',
      standings: 'tabela',
      matchday: 'kolo',
    },
    lexicon: {
      history: 'istorija',
      thousand: 'hiljada',
      week: 'nedelja',
      coffee: 'kafa',
      air: 'vazduh',
      what_interrogative: 'šta',
    },
    grammarRules: [
      'Koristi EKAVICU: mleko, lep, dete, svet, reka',
      'Koristi LATINICU',
      'Preferirati da+prezent: želim da idem',
      'Budućnost: imaću (spojeno)',
    ],
    forbiddenTerms: [
      'nogomet', 'vratar', 'sudac', 'momčad', 'tisuća',
      'povijest', 'glazba', 'zaleđe', 'tjedan',
    ],
  },
  'sr-Cyrl': {
    code: 'sr-Cyrl',
    name: 'Serbian (Cyrillic)',
    nativeName: 'Српски',
    script: 'cyrillic',
    dialect: 'ekavica',
    sportTerms: {
      football: 'fudbal',
      team: 'tim',
      match: 'utakmica',
      goal: 'gol',
      goalkeeper: 'golman',
      referee: 'sudija',
      penalty: 'penal',
      offside: 'ofsajd',
      corner: 'korner',
      halftime: 'poluvreme',
      victory: 'pobeda',
      defeat: 'poraz',
      draw: 'nerešeno',
      shot: 'udarac',
      shots_on_target: 'udarci u okvir',
      possession: 'posed lopte',
      foul: 'prekršaj',
      yellow_card: 'žuti karton',
      red_card: 'crveni karton',
      substitution: 'izmena',
      assist: 'asistencija',
      standings: 'tabela',
      matchday: 'kolo',
    },
    lexicon: {
      history: 'istorija',
      thousand: 'hiljada',
      week: 'nedelja',
      coffee: 'kafa',
      air: 'vazduh',
      what_interrogative: 'šta',
    },
    grammarRules: [
      'Koristi EKAVICU: mleko, lep, dete, svet, reka',
      'Koristi ĆIRILICU za output',
      'Preferirati da+prezent: želim da idem (ne: želim ići)',
      'Budućnost: imaću (spojeno)',
      'Upitna zamjenica: šta',
    ],
    forbiddenTerms: [
      'nogomet', 'vratar', 'sudac', 'momčad', 'tisuća',
      'povijest', 'glazba', 'zaleđe', 'tjedan',
    ],
  },
  cnr: {
    code: 'cnr',
    name: 'Montenegrin',
    nativeName: 'Crnogorski',
    script: 'latin',
    dialect: 'ijekavica',
    sportTerms: {
      football: 'fudbal',
      team: 'tim',
      match: 'utakmica',
      goal: 'gol',
      goalkeeper: 'golman',
      referee: 'sudija',
      penalty: 'penal',
      offside: 'ofsajd',
      corner: 'korner',
      halftime: 'poluvrijeme',
      victory: 'pobjeda',
      defeat: 'poraz',
      draw: 'nerješeno',
      shot: 'udarac',
      shots_on_target: 'udarci u okvir',
      possession: 'posjed lopte',
      foul: 'prekršaj',
      yellow_card: 'žuti karton',
      red_card: 'crveni karton',
      substitution: 'izmjena',
      assist: 'asistencija',
      standings: 'tabela',
      matchday: 'kolo',
    },
    lexicon: {
      history: 'istorija',
      thousand: 'hiljada',
      week: 'neđelja',
      coffee: 'kafa',
      air: 'vazduh',
      what_interrogative: 'šta',
    },
    grammarRules: [
      'Koristi IJEKAVICU: mlijeko, lijep, dijete, svijet, rijeka',
      'Koristi LATINICU',
      'Specifične crnogorske forme: nijesmo (ne: nismo), đe (ne: gdje)',
      'Opciono: slova ś i ź (sjekira → śekira)',
      'Budućnost: imaću (spojeno)',
    ],
    forbiddenTerms: [
      'nogomet', 'vratar', 'sudac', 'momčad', 'tisuća',
      'povijest', 'glazba', 'zaleđe', 'tjedan',
      'mleko', 'lep', 'pobeda',
    ],
  },
  en: {
    code: 'en',
    name: 'English',
    nativeName: 'English',
    script: 'latin',
    dialect: 'none',
    sportTerms: {
      football: 'football',
      team: 'team',
      match: 'match',
      goal: 'goal',
      goalkeeper: 'goalkeeper',
      referee: 'referee',
      penalty: 'penalty',
      offside: 'offside',
      corner: 'corner',
      halftime: 'half-time',
      victory: 'victory',
      defeat: 'defeat',
      draw: 'draw',
      shot: 'shot',
      shots_on_target: 'shots on target',
      possession: 'possession',
      foul: 'foul',
      yellow_card: 'yellow card',
      red_card: 'red card',
      substitution: 'substitution',
      assist: 'assist',
      standings: 'standings',
      matchday: 'matchday',
    },
    lexicon: {},
    grammarRules: ['British English spelling preferred', 'AP Style for sports reporting'],
    forbiddenTerms: [],
  },
  ar: {
    code: 'ar',
    name: 'Arabic',
    nativeName: 'العربية',
    script: 'arabic',
    dialect: 'none',
    sportTerms: {
      football: 'كرة القدم',
      team: 'فريق',
      match: 'مباراة',
      goal: 'هدف',
      goalkeeper: 'حارس المرمى',
      referee: 'حكم',
      penalty: 'ركلة جزاء',
      offside: 'تسلل',
      corner: 'ركلة ركنية',
      halftime: 'الشوط الأول',
      victory: 'فوز',
      defeat: 'هزيمة',
      draw: 'تعادل',
      shot: 'تسديدة',
      shots_on_target: 'تسديدات على المرمى',
      possession: 'استحواذ',
      foul: 'مخالفة',
      yellow_card: 'بطاقة صفراء',
      red_card: 'بطاقة حمراء',
      substitution: 'تبديل',
      assist: 'تمريرة حاسمة',
      standings: 'الترتيب',
      matchday: 'الجولة',
    },
    lexicon: {},
    grammarRules: ['Modern Standard Arabic (MSA)', 'Right-to-left text direction'],
    forbiddenTerms: [],
  },
  tr: {
    code: 'tr',
    name: 'Turkish',
    nativeName: 'Türkçe',
    script: 'latin',
    dialect: 'none',
    sportTerms: {
      football: 'futbol',
      team: 'takım',
      match: 'maç',
      goal: 'gol',
      goalkeeper: 'kaleci',
      referee: 'hakem',
      penalty: 'penaltı',
      offside: 'ofsayt',
      corner: 'köşe vuruşu',
      halftime: 'devre arası',
      victory: 'galibiyet',
      defeat: 'mağlubiyet',
      draw: 'beraberlik',
      shot: 'şut',
      shots_on_target: 'isabetli şut',
      possession: 'top hakimiyeti',
      foul: 'faul',
      yellow_card: 'sarı kart',
      red_card: 'kırmızı kart',
      substitution: 'oyuncu değişikliği',
      assist: 'asist',
      standings: 'puan durumu',
      matchday: 'hafta',
    },
    lexicon: {},
    grammarRules: ['Turkish Latin alphabet with special chars: ç, ğ, ı, ö, ş, ü'],
    forbiddenTerms: [],
  },
};

/**
 * Get language config, with fallback to Bosnian.
 */
export function getLanguageConfig(code: string): LanguageConfig {
  // Handle sr mapping — bare 'sr' defaults to Cyrillic
  if (code === 'sr') return LANGUAGE_CONFIGS['sr'];
  return LANGUAGE_CONFIGS[code] || LANGUAGE_CONFIGS['bs'];
}

/**
 * Generate language-specific prompt section for the AI engine.
 */
export function getLanguagePromptSection(config: LanguageConfig): string {
  let prompt = `\nJEZIK: ${config.nativeName} (${config.code})\nDIJALEKT: ${config.dialect === 'none' ? 'N/A' : config.dialect}\nPISMO: ${config.script}\n`;

  prompt += `\nGRAMATIČKA PRAVILA:\n`;
  for (const rule of config.grammarRules) {
    prompt += `- ${rule}\n`;
  }

  if (config.forbiddenTerms.length > 0) {
    prompt += `\n★★★ ZABRANJENE RIJEČI (iz pogrešne jezičke varijante — NE KORISTI) ★★★\n`;
    prompt += config.forbiddenTerms.join(', ') + '\n';
    prompt += `★★★ KRAJ ZABRANJENIH RIJEČI ★★★\n`;
  }

  prompt += `\nSPORTSKA TERMINOLOGIJA (OBAVEZNO KORISTITI OVE TERMINE):\n`;
  for (const [key, value] of Object.entries(config.sportTerms)) {
    prompt += `- ${key}: ${value}\n`;
  }

  return prompt;
}
